### ISSUE TITLE
Is simulation still possible? (Icarus or otherwise)

### ISSUE THREAD

**Issue by waskiewi** [open-sdr/openwifi#10]
Commit 10ff8da3d71d for openOfdm_rx submodule changed the Viterbi and FFT modules from older IP cores to AXI ip cores.  After this change - is it possible to simulate the _rx or _tx ip cores with Icarus (or something else?)

**Comment by JiaoXianjun** [comment]
Yes. RX and tx core can run in simulation. We have verified that when developing.

**Comment by waskiewi** [comment]
Is that simulation available in the openwifi repo somewhere? I apologize, I am not seeing it.

**Comment by JiaoXianjun** [comment]
No. The unit test bench is not available in the repository.
