### ISSUE TITLE
WIFI signal is weak in antsdr E310

### ISSUE THREAD

**Issue by guanliliang123** [open-sdr/openwifi#109]
I use antsdr E310 running with OpenWIFI on it.
But I found that its WIFI signal is relatively weak, even if my device is close to it, it only has a three-segment signal.
The seller suggested that I add an amplifier, but I don’t know the parameters it needs.
Can you give me some suggestions?

**Comment by JiaoXianjun** [comment]
If no further questions, I will close this issue.
