### ISSUE TITLE
Hard to scan the SSID and cannot connect to the openwifi

### ISSUE THREAD

**Issue by HC153Yuanyuan** [open-sdr/openwifi#113]
My board is antsdr b220. I am running the openwifi project and found that when I working in 5GHz, the sniffer could not capture any beacon. When I switched to 2.4GHz, although I could capture  beacon frame through wireshark, it was difficult for the phone to scan the SSID. When I try to connect, it always fails.

![2021-10-22 22-43-47屏幕截图](https://user-images.githubusercontent.com/43514189/138476410-861ff541-7f79-4179-8f9d-1f88b5dba88c.png)

![2021-10-22 22-44-27屏幕截图](https://user-images.githubusercontent.com/43514189/138476414-487d4dad-4ee6-4a56-a5b2-ce851786e54f.png)

What do you think about this ？

**Comment by JiaoXianjun** [comment]
If no further questions, I will close this issue.
