### ISSUE TITLE
openwifi capture interval N

### ISSUE THREAD

**Issue by gxhen** [open-sdr/openwifi#127]
Hi xianjun, I am using the IQ capture program to collect Wi-Fi packets. I am confused by the definition of capture interval N in the command 'side_ch_ctl gN'. Is it the interval that FPGA board performs the packet detection algorithm? If my Wi-Fi transmission interval is less than the default value 100ms (for example 50ms), do I need to reduce N correspondingly to prevent packet loss? Many thanks.

**Comment by JiaoXianjun** [comment]
That is the interval of how frequent the side_ch driver will check the FPGA buffer.
If you don't want loss, you can specify N as 0 to let the side_ch driver check FPGA buffer as fast as possible.

**Comment by gxhen** [comment]
Thanks very much for your clear explanation.
