### ISSUE TITLE
CSI and Wifi packet

### ISSUE THREAD

**Issue by GuanLiliang** [open-sdr/openwifi#129]
Board/hardware type
AntSDR E310
WiFi channel number
44
1. How to match the timestamp in CSI to the timestamp in WiFi packet capture software such as wireshark? Are there similar examples in the project?
2. Our board has 2 rx and 2 tx, each packet received contains 4 data streams, do these 4 data streams correspond to the antenna or random?

**Comment by JiaoXianjun** [comment]
1. You need to check the timestamp captured by openwifi I/Q capture function and wireshark. The timestamp is in us, and you need to compare each timestamp (from both sides: openwifi IQ capture and wireshark) to find out which one is the closest, then that I/Q is matched to that packet.
2. You need to read https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/iq.md and https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/iq_2ant.md carefully.

**Comment by JiaoXianjun** [comment]
yes
