### ISSUE TITLE
iq_capture app

### ISSUE THREAD

**Issue by Shangjie-Yang** [open-sdr/openwifi#131]
Hi,
    I am having the following problem with the iq_capture tool.
    I send a continuous IQ signal and use the iq_capture tool to capture it, but each time I capture 4094 symbols it interrupts once, and after the interruption there is a delay before continuing the capture, and the delay is not fixed.
    Then I modified the 'wh11d4094' instruction to 'wh11d8187',  after the modification, the phenomenon became that there was an interrupt after every 8187 symbols were captured, and the interrupt generated a time delay and caused some data to be missed.
    I would like to know the reason for the delay,and what is the way to avoid these delays, or make these delays into a fixed value.
    Thanks.
![image](https://user-images.githubusercontent.com/75883882/147222337-594e5281-b4e9-4ebb-8787-abf440f8cd95.png)

**Comment by JiaoXianjun** [comment]
Can you share me the full command sequence? Then I will try to reproduce it.

**Comment by JiaoXianjun** [comment]
Can you also answer all questions in our issue template? Those information are very important for us to understand the issue.

**Comment by chenmo234** [comment]
Hello, sorry to bother you. May I ask you some questions regarding IQ capture in OpenWiFi? Here is my contact information: c2385405729.
