### ISSUE TITLE
 modulation.v, such as 16'hBEA0, how does this BEA0 come from? 

### ISSUE THREAD

**Issue by peking428** [open-sdr/openwifi#138]
I don't understand the data under 64QAM in the code file modulation.v, such as 16'hBEA0, how does this BEA0 come from? How to calculate it?

**Comment by JiaoXianjun** [comment]
You could convert those hex number to signed 16bit integer and plot them in the constellation square, then I believe you will understand.

**Comment by peking428** [comment]
thank you!



---- 回复的原邮件 ----
| 发件人 | Jiao ***@***.***> |
| 日期 | 2022年02月22日 23:22 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [open-sdr/openwifi] modulation.v, such as 16'hBEA0, how does this BEA0 come from? (Issue #138) |

You could convert those hex number to signed 16bit integer and plot them in the constellation square, then I believe you will understand.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
