### ISSUE TITLE
Whether openwifi supports TDD mode. How to capture information like Bit Error Rate (BER) or Packet Error Rate (PER

### ISSUE THREAD

**Issue by EvCong24601** [open-sdr/openwifi#141]
1. Our image is used directly or you build your own image?
Use the openwifi image.
3. Ubuntu 18.04, Vivado 2018.3, openwifi/openwifi-hw repo branch and commit revision
4. Board/hardware type
zed_fommcs3
5. WiFi channel number
44

Thanks for the great efforts your team have made on the openwifi. 
My question is quite straightforward. First,whether openwifi supports TDD mode. In the HDL design, the axi_ad9361 ip is set to support TDD mode. I read the ip_guide provided by ADI. Here i want to comfire it.
Second how can i get information like Bit Error Rate (BER) or Packet Error Rate (PER) to evaluate its radiation quality.

**Comment by JiaoXianjun** [comment]
Please check these app note for PER and many other statistics:
https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/inject_80211.md
https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/perf_counter.md
https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/driver_stat.md
