### ISSUE TITLE
Do you have top module(rx_intf,xpu,tx_intf) and what is low Mac The frame format

### ISSUE THREAD

**Issue by zhuzhineng** [open-sdr/openwifi#146]
0. Could you send email to xianjun.jiao@ugent.be to introduce your self?

1. Our image is used directly or you build your own image?

2. What is your own modification?

3. Versions: OS, Vivado, openwifi/openwifi-hw repo branch and commit revision

4. Board/hardware type

5. WiFi channel number

6. Steps to reproduce the issue, and the related error message, screenshot, etc

7. Describe your debug efforts by Linux native tools, such as tcpdump and "cat /proc/interrupts"

8. Describe your debug efforts by: https://github.com/open-sdr/openwifi/blob/master/doc/README.md#Debug-methods

9. Any other thing we need to know for helping you better?

**Comment by JiaoXianjun** [comment]
Please follow this readme: https://github.com/open-sdr/openwifi-hw/blob/master/README.md , this section : https://github.com/open-sdr/openwifi-hw#Build-FPGA 
to generate Vivado top leve project, then you will see top module openwfi_ip like in this figure:
![openwifi_ip](https://user-images.githubusercontent.com/5212105/159030356-2f802590-127d-4d3e-b909-dd3fefb5a43d.jpg)

**Comment by zhuzhineng** [comment]
thank you



---Original---
From: "Jiao ***@***.***&gt;
Date: Fri, Mar 18, 2022 23:17 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-sdr/openwifi] Do you have top module(rx_intf,xpu,tx_intf)and what is low Mac The frame format (Issue #146)




 
Please follow this readme: https://github.com/open-sdr/openwifi-hw/blob/master/README.md , this section : https://github.com/open-sdr/openwifi-hw#Build-FPGA
 to generate Vivado top leve project, then you will see top module openwfi_ip like in this figure:
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
