### ISSUE TITLE
How can I realize getting CSI information of ping command from each other in ad-hoc mode

### ISSUE THREAD

**Issue by GuanLiliang** [open-sdr/openwifi#148]
I have two boards of ANTSDR. Now I am willing to realize getting CSI information of each other. Therefore, my thought is that two boards will work in ad-hoc mode. However, I saw you had got CSI information in the monitor mode, at page of CSI notes. How can I realize getting CSI information of ping command from each other in ad-hoc mode?

**Comment by JiaoXianjun** [comment]
https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/csi.md#run-the-csi-together-with-modes-other-than-monitor
