### ISSUE TITLE
Unable to successfully get csi information

### ISSUE THREAD

**Issue by xiaoxiaochuzm** [open-sdr/openwifi#150]

**Comment by CaptainiFalcon** [comment]
I meet the same problem as @xiaoxiaochuzm

**Comment by JiaoXianjun** [comment]
Could you share us the exact information of:
1. The step by step commands/operations you have run (also tell us that operation is performed on board or on computer)
2. The output and phenomenon you observed in each step

**Comment by xiaoxiaochuzm** [comment]
I'm so sorry to bother you. I think I made a low-level mistake. I didn't turn off the computer firewall in time, which led to the received message of 0.Thank you very much for your timely reply.

**Comment by JiaoXianjun** [comment]
No worry. Good luck. 

Seems like you are using windows? We always use Linux.

**Comment by chenmo234** [comment]
Hello, sorry to bother you. May I ask you some questions regarding IQ capture in OpenWiFi? Here is my contact information: c2385405729.
