### ISSUE TITLE
When I connected to AP, I encountered the following error

### ISSUE THREAD

**Issue by Mrxia111** [open-sdr/openwifi#154]
![3](https://user-images.githubusercontent.com/92384670/161421404-e8e4be05-dda3-4d51-abe5-f5c0922e4b11.png)
As shown in the figure, when I want to connect to AP, the following error occurs
![1](https://user-images.githubusercontent.com/92384670/161421454-e8d0cd70-fbf8-4d45-9e83-a06d72096b60.png)
this is my wpa-connect.conf file.
![2](https://user-images.githubusercontent.com/92384670/161421481-dba5ddfe-3472-4bf5-82f1-9e3ceb4cec40.png)
how can i address? could give me some advice.

**Comment by JiaoXianjun** [comment]
Could you answer questions in our template? Without knowing those info, it is difficult for us to tell what is the issue.

**Comment by JiaoXianjun** [comment]
can you use other client (phone/laptop) connect that AP?

what is the channel number of that AP?

can you set your AP to a channel in 5GHz instead of 2.4GHz?

what is the distance from your AP to openwifi. 

Can you configure your AP into 11ag or 11n mode (not ac or ax).

Can you run “ iwlist sdr0 scan” on openwifi board, and share me output.

**Comment by JiaoXianjun** [comment]
Also check your antenna connection. You need two antennas connected to tx and rx port. What is your RF board?

**Comment by JiaoXianjun** [comment]
If you follow the quick start guide to setup openwifi AP, can you use your phone/laptop to connect to openwifi AP?

**Comment by Mrxia111** [comment]
many computer can use this AP&nbsp;


this is picture which is using my phone to connect AP&nbsp;



that AP is close


I can run “ iwlist sdr0 scan” on openwifi board,&nbsp;










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-sdr/openwifi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月3日(星期天) 晚上7:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-sdr/openwifi] When I connected to AP, I encountered the following error (Issue #154)





 
can you use other client (phone/laptop) connect that AP?
 
what is the channel number of that AP?
 
can you set your AP to a channel in 5GHz instead of 2.4GHz?
 
what is the distance from your AP to openwifi.
 
Can you configure your AP into 11ag or 11n mode (not ac or ax).
 
Can you run “ iwlist sdr0 scan” on openwifi board, and share me output.
