### ISSUE TITLE
Question: Will generic tasks on ARM cores affect the performance of mac80211?

### ISSUE THREAD

**Issue by sada45** [open-sdr/openwifi#156]
Hi xianjun!
The openWiFi seperates the MAC layer into low-MAC and high-MAC. The high-MAC is based on the mac80211 subsystem in the linux kernel. 
Here is my question, if there are some generic tasks (e.g., a web server, a lightweight DNN) running on the linux and the system is heavy loaded, will the performance of 802.11 decrease?
Or, the thread of mac80211 has highest priority, so the generic tasks can not preempt it?

**Comment by JiaoXianjun** [comment]
We only developed the driver and FPGA. For the Linux kernel and mac80211 framework above, it is what it is. 

So I don’t know. 

You need to find out by yourself. Looking forward to your answer.

**Comment by sada45** [comment]
Alright, we have just order a antSDR to try this project :)
