### ISSUE TITLE
CSI data source

### ISSUE THREAD

**Issue by Eugene-Liu-Incubator** [open-sdr/openwifi#157]
Hi, I am looking to do some experiments with SDR using openwifi on Analog Device adrv9364z7020 hardware.

I am using 802.11a to my experiment, and I would like to know the source of CSI in Openwifi.

Is it comes from long training symbol in I/Q ?

Or only the pilot subcarriers (-21, -7, 7, 21) in long training symbol and interpolation to all subcarriers ?

Thanks for your openwifi project, this quite helpful for us to improve our research.

Sincerely,
Eugene Liu.

**Comment by JiaoXianjun** [comment]
csi comes from long training symbol.

**Comment by Eugene-Liu-Incubator** [comment]
Thanks for your reply !
