### ISSUE TITLE
zcu102_fmcs2 SD card img download link dead

### ISSUE THREAD

**Issue by A-T-Kristensen** [open-sdr/openwifi#165]
Hello,

The download link for the zcu102_fmcs2 SD card image is dead, the link returns

**Not Found
The requested URL /~xjiao/openwifi-1.2.0-leuven-2-64bit.img.xz was not found on this server.**

Thank you for your help

**Comment by JiaoXianjun** [comment]
The image has been upgraded. You can find the latest image link in the README.

**Comment by A-T-Kristensen** [comment]
Thank you for the quick reply.
