### ISSUE TITLE
About module 'phy_rx_parse.v'

### ISSUE THREAD

**Issue by gxhen** [open-sdr/openwifi#166]
Hi Dr Jiao, I am learning about your FPGA implementation recently and found a module named **'phy_rx_parse.v'**. There are several questions that I would like to ask:
1. This module accepts decoded OFDM bytes and outputs addr1, 2, 3, etc. Does this mean that the MAC addresses contained in the received packets are available on FPGA and can be added to the side_info?
2. Can this module also be used on N210? I remember you mentioned the FPGA on N210 is of limited computing resources and cannot run modules other than openOFDM rx (dot11.v). Does the module **'phy_rx_parse.v'** require lots of computing resources?

Thanks in advance.

**Comment by JiaoXianjun** [comment]
1 yes
2 We don't know. You need to try.
