### ISSUE TITLE
ZC706 dangling pins

### ISSUE THREAD

**Issue by chs9996** [open-sdr/openwifi#168]
Running ip_repo_gen.tcl then openwifi.tcl leaves two unconnected inputs on the openwifi IP. They are dma-valid and dma_data[63:0]. 
These two inputs were not on the openwifi IP for the zed board so why have they appeared on the zc706 ? 
How to fix this  please ?

**Comment by JiaoXianjun** [comment]
They are useless. Just move forward.

**Comment by chs9996** [comment]
Working with these ignored :) Thanks
