### ISSUE TITLE
two questions

### ISSUE THREAD

**Issue by GuanLiliang** [open-sdr/openwifi#172]
1. Can I use the board to get TSF register value by any api functions?
2. When I use two boards in ad-hoc mode with 1 rx and 1 tx to get csi, I found there may be more than 1 csi information corresponding to 1 packet. What leads to the result? Is it multipath effect?

**Comment by JiaoXianjun** [comment]
1. search "tsf" in our project document (not the front page readme)
2. that is not multipath. if side_ch_ctl runs at interval longer than your packet interval, it might collect CSI of more than 1 packet.
