### ISSUE TITLE
some question about linux runing on my own board

### ISSUE THREAD

**Issue by YideTian** [open-sdr/openwifi#173]
hello, My own board is based on xc7z030 , and i have done some modification for my board:
1. Modify the DDR configuration and MIO constrain. The same constrain is been tested for another SD card, which  has petalinux inside. The console shows that the system is boot successfuly. So the uart(UART0) chain and DDR would be right.
2. I modified the .xdc file and change the pin location to my own board.
3. Add two led module to system_top. one module is driven by PL side clock, and another clock is from zynq ip FCLK_CLK0. 
4. I'm using "adrv9361z7035" as my board name to generate boot bin.
then i "Build openwifi Linux img from scratch" as README construction said.
my BOOT partion is like this:
![screenshot_3](https://user-images.githubusercontent.com/17080046/168761142-b88186a1-b194-4377-a9be-ca0a620e0754.png)
the problem is:
Those two led is flashing on power up. so i guess fsbl is success. But i haven't seen any output in uart console yet. Could you help me find the problem? Thank you!

**Comment by cjhonlyone** [comment]
Hi, YideTian
You should check hdf status and u-boot compiling process.
u-boot is not too much association with hardware.
Check whether FPGA is programed properly by fsbl.
Good Luck!

**Comment by YideTian** [comment]
@cjhonlyone Hi, Thank you for your response. 
I have checked the DDR, I think it's ok ,The hdf is up to date. Then i modify the device tree and run update_sdcard.sh. The result has no difference. I guess u-boot should be changed properly.
But i don't know how to deal with u-boot. May i ask for your email address? So that i can ask you about some details. Thanks again for your kindness help!

**Comment by cjhonlyone** [comment]
@YideTian cjh416593819@gmail.com

**Comment by YideTian** [comment]
@cjhonlyone Thank you!
