### ISSUE TITLE
Should I modify the FPGA?

### ISSUE THREAD

**Issue by ggsnpdsn** [open-sdr/openwifi#175]
I ask an entry-level question: if you do not use CSMA / Ca mechanism and use TDMA instead, do you only need to modify MAC or FPGA? How to solve the problem of synchronous clock?

**Comment by JiaoXianjun** [comment]
hard to say, since you are designing sth new, that we do not have in this repository.
you need to figure out by yourself.

if you have questions towards the code in this repository, you can ask.
