### ISSUE TITLE
Questions about synchronization

### ISSUE THREAD

**Issue by BZZDKBRS** [open-sdr/openwifi#177]
Does openwifi realize the synchronization function? If so, how is it achieved? thank you!

**Comment by JiaoXianjun** [comment]
I don't know. Could you explain in detail what is the synchronization you want?

**Comment by JiaoXianjun** [comment]
The driver and FPGA only passes the necessary information between upper layer/Linux and the antenna (such as the packet and its TSF timestamp, etc.), and it only executes setting from upper layer/Linux.

The functionality you described is in upper layer I think.

Or, you have all driver and Linux source code, I think you can also try to implement this functionality.

**Comment by JiaoXianjun** [comment]
You can also check our paper on synchronization on this page: https://github.com/open-sdr/openwifi/blob/master/doc/publications.md

**Comment by BZZDKBRS** [comment]
Thank you very much.
