### ISSUE TITLE
How to set openwifi work at arbitrary frequency ?

### ISSUE THREAD

**Issue by reuncc** [open-sdr/openwifi#181]
I  have two devices , one is master, the other is slave,
The master device executethe follow commands:
   1  ./sdrctl dev sdr0 set reg rf 1 1457
   2  ./sdrctl dev sdr0 set reg rf 5 1457
   3  ./wgd.sh
   4  ./fosdem-11ag.sh
The slave device is setted to follow commanders:
 wpa-connect.conf ，the master's ssid:openwifi  , password :12345678
 then the slave executethe follow commands:
   1 ./wgd.sh
   2 ./sdrctl dev sdr0 set reg rf 1 1457
   3 ./sdrctl dev sdr0 set reg rf 5 1457
   4 route del default gw 192.168.10.1
   5 wpa_supplicant -i sdr0 -c wpa-connect.conf &
   6 dhclient sdr0

Under these conditions ,the terminal show these:  [sdr0: CTRL-EVENT-SCAN-STARTED]

But if I don't execute sdrctl(1/2),ether the master or the slave, the terminal show connected.

So, I want to know how to build connect as above commands,  I need how to set my devices???

Thanks!!!

**Comment by JiaoXianjun** [comment]
Do the normal connection in a normal channel firstly. After you connect successfully, do the sdrctl command at both sides (AP and client)

**Comment by reuncc** [comment]
Cannot modify before connecting?

**Comment by JiaoXianjun** [comment]
Have you tried successfully?
If no further issue, I will close this one.
