### ISSUE TITLE
请问Linux/arm 4.14.0 Kernel Configuration版本在哪

### ISSUE THREAD

**Issue by Flynnsin** [open-sdr/openwifi#182]
0. Could you send email to xianjun.jiao@ugent.be to introduce your self?

1. Our image is used directly or you build your own image?

2. What is your own modification?

3. Versions: OS, Vivado, openwifi/openwifi-hw repo branch and commit revision

4. Board/hardware type

5. WiFi channel number

6. Steps to reproduce the issue, and the related error message, screenshot, etc

7. Describe your debug efforts by Linux native tools, such as tcpdump and "cat /proc/interrupts"

8. Describe your debug efforts by: https://github.com/open-sdr/openwifi/blob/master/doc/README.md#Debug-methods

9. Any other thing we need to know for helping you better?

**Comment by JiaoXianjun** [comment]
1. Please use English.
2. Could you elaborate the question? I don't understand.

**Comment by Flynnsin** [comment]
Sorry, it's done

A new problem has arisen

operation fosdem-11ag.sh

Everything was normal in the early days，generate sdr0 Ethernet port

but
./fosdem.sh: line 16: hostapd: command not found
./fosdem.sh: line 19: webfsd: command not found

Hot spot cannot be opened

**Comment by Flynnsin** [comment]
Why can I not connect to a hotspot when it is enabled
