### ISSUE TITLE
Recompile sdr.ko run wgd.sh has problems

### ISSUE THREAD

**Issue by 8663** [open-sdr/openwifi#191]
Getting this error when run wgd.sh:
Run wgd.sh appears when loads the recompiled driver ssdr.ko has a problem

root@analog:~/openwifi# ./wgd.sh

![image](https://user-images.githubusercontent.com/109722782/180158265-c3bd5f8c-834e-4eef-8e52-69d64b63c765.png)

**Comment by JiaoXianjun** [comment]
You need to describe step by step exact operations you have done from the beginning (also the output of the command you run). From downloading of software, our repository, SD card image, etc., to how do you compile the sdr.ko/kernel, how to put it onboard, etc.
You also need to describe the exact version of your OS, Vivado, etc.

**Comment by 8663** [comment]
The operating system we used was ubuntu16.04,Vivado is 2017.4
The whole process:
git init
git pull https://github.com/open-sdr/openwifi.git
programming environment setup：
export XILINX_DIR=/opt/Xilinx
source /opt/pkg/petalinux/settings.sh
source /opt/Xilinx/Vivado/2017.4/settings64.sh
![image](https://user-images.githubusercontent.com/109722782/180173632-4eb76754-eb5e-49c9-b037-865120a9e998.png)

![image](https://user-images.githubusercontent.com/109722782/180173894-6fc3edcf-e658-43da-bc78-637a7077b653.png)

**Comment by JiaoXianjun** [comment]
Sorry that we do not have that Vivado version, and hard to reproduce the issue in the Vivado 2018.3 we suggested.

I suggest you use Ubuntu18 or 20 LTS together with Vivado 2018.3.

**Comment by chenmo234** [comment]
I also need to modify sdr.c and perform the same operations as you. Can I discuss this with you? Here is my contact information: c2385405729.
