### ISSUE TITLE
1.1.0镜像 zc706 kernel panic

### ISSUE THREAD

**Issue by jiskra** [open-sdr/openwifi#20]
利用做好的镜像文件用zc706+fmcomms3进行实验时，工作在ap模式，终端链接会出现kernel panic。重新编译kernel，无法建立sdr0网卡。

**Comment by JiaoXianjun** [comment]
Hello,

Would you please try this new image (openwifi-1.1.0-taiyuan-3-32bit.img.xz) to see whether the crash issue is gone?
https://drive.google.com/file/d/1DuSlHjLq9WQGvUv-0VNElqemQL_k3dPc/view?usp=sharing

I have fixed the potential crash issue by improving FPGA and driver involving more safe and exception tolerant design.

If your test give me positive result, I will update the source code to this git repository soon.

Thanks!

**Comment by JiaoXianjun** [comment]
Hello,

How are you doing with openwifi now? Do you still have any issue? The openwifi has been improved a lot during the last .5 year. It supports more boards (high end to low end) and becomes more stable. 

Would you please tell us your email? If you could also introduce yourself bit (student? Company? University?), that would be perfect. We might send out some questions to listen for user feed feedback.
Thanks

**Comment by jiskra** [comment]
我研究所工作的，学通信的，openwifi这个项目很棒，问题的话我用的问题主要 1.丢包比较厉害 2.还是不是特别稳定 打持续大流量会直接死 复位才可以








--------From 吕晨阳
上帝的恩赐也需要俯身虔诚地采收。





在2020年08月01 03时48分，"Jiao Xianjun"<notifications@github.com>写道：


Hello,
How are you doing with openwifi now? Do you still have any issue? The openwifi has been improved a lot during the last .5 year. It supports more boards (high end to low end) and becomes more stable.
Would you please tell us your email? If you could also introduce yourself bit (student? Company? University?), that would be perfect. We might send out some questions to listen for user feed feedback.
Thanks
