### ISSUE TITLE
Can not download the image

### ISSUE THREAD

**Issue by chubohao** [open-sdr/openwifi#200]
Hi,

I can not download the image from this branch.
![image](https://user-images.githubusercontent.com/31478831/184534104-f13bdf99-bbd6-4510-8cec-0feec4257871.png)

Best wishes and looking forward to your reply.

**Comment by JiaoXianjun** [comment]
If you follow our readme, you can find link of the image from the latest release.

**Comment by chubohao** [comment]
> If you follow our readme, you can find link of the image from the latest release.

Thanks, it works now.
