### ISSUE TITLE
 Which DMA hardware is used in openwifi driver?

### ISSUE THREAD

**Issue by feiger313** [open-sdr/openwifi#204]
Please ask whether the DMA used in the driver is from the FPD_DMA in the PS or the AXI_DMA in the pl?

**Comment by JiaoXianjun** [comment]
tx dma https://github.com/open-sdr/openwifi/blob/c6dd9e71e5a911d3150bcd980890353e9bd4b066/kernel_boot/boards/zed_fmcs2/devicetree.dts#L844

rx dma https://github.com/open-sdr/openwifi/blob/c6dd9e71e5a911d3150bcd980890353e9bd4b066/kernel_boot/boards/zed_fmcs2/devicetree.dts#L872

**Comment by feiger313** [comment]
Thank you, Dr. Jiao, for understanding this problem.
	`priv->tx_chan` = dma_request_slave_channel(&(priv->pdev->dev), "tx_dma_mm2s"); 
It turns out that "tx_dma_mm2s" will associate the device tree
