### ISSUE TITLE
SDR with 802.11ax Feature

### ISSUE THREAD

**Issue by meena-devi** [open-sdr/openwifi#205]
Hi,

Thank you in advance.

1. As you have mentioned the 802.11ax feature is under development. May I please know if any update on it.

2. I wanted to run the code base on usrp b210 with 802.11 ax feature. So does the openwifi supports for SDR - usrp b210?

Regards,
meena-devi

**Comment by JiaoXianjun** [comment]
1. We are working on it. It is quite complicated, so the progress is slower than our expectation
2. We never try b210. You need to figure out how to run/port it yourself.

**Comment by meena-devi** [comment]
> 1. We are working on it. It is quite complicated, so the progress is slower than our expectation
> 
>     2. We never try b210. You need to figure out how to run/port it yourself.

Thank you so much for your response
