### ISSUE TITLE
Cable Connection

### ISSUE THREAD

**Issue by Qiu2333** [open-sdr/openwifi#208]
Hi, Dr. Jiao!
Thank you in advance for your team's groundbreaking work!
I want to connect **two openwifis** or **an openwifi and a commertial NIC** with **cables**.
Are attenuators necessary?
Or does their transmit power need to be reduced?

**Comment by JiaoXianjun** [comment]
The Tx power is around -12 or -15dBm (depends a bit the band you set). With this number, you can decide whether you need attenuation or not. Normally you'd better use one (such as 30dB attenuation)
