### ISSUE TITLE
关于接收与发送频偏问题

### ISSUE THREAD

**Issue by melodywxl** [open-sdr/openwifi#212]
Hello, why do you need to set the sending and receiving frequency to a frequency offset of 10MHz to send and receive messages normally? Will it affect the busyness detection and message sending and receiving of wifi itself? In the frequency band, because the channel is busy, it often occurs that the message cannot be received, or the sender cannot receive the ACK response from the peer.

**Comment by JiaoXianjun** [comment]
Where did you get this "... offset of 10MHz"?

**Comment by melodywxl** [comment]
Thank you very much for your reply. Maybe the local code is too old. I re-read the new version of the code you released, and it is true that there is no frequency offset.
