### ISSUE TITLE
Can you still use the gnuradio features of the ADI design with this design?

### ISSUE THREAD

**Issue by davidfhorowitz** [open-sdr/openwifi#218]
### Discussed in https://github.com/open-sdr/openwifi/discussions/215

<div type='discussions-op-text'>

<sup>Originally posted by **davidfhorowitz** September 14, 2022</sup>
Hello, 

I am running your design on a ADI PackRF (ADRV9361-Z7035) and it works great! I am trying to also implement a gnu radio block design using gnu radio companion that I'd like to run when your design is not running. Is this possible with the design as it is now or would it need modifications to the software and/or HDL? Right now I'm having issues getting gnu radio to run. 

Thank you, 

-David </div>

**Comment by JiaoXianjun** [comment]
https://github.com/open-sdr/openwifi/discussions/215
