### ISSUE TITLE
There was a problem executing./wgd.sh

### ISSUE THREAD

**Issue by 8663** [open-sdr/openwifi#219]
At execution time of ./make_all.sh $XILINX_DIR 32，something went wrong
![image](https://user-images.githubusercontent.com/109722782/190584851-c3bb3e7e-49e2-446f-8099-2cdac6507c51.png)
![image](https://user-images.githubusercontent.com/109722782/190585552-0328decc-d0b9-45e9-b8f7-62fc64f69ff4.png)
![image](https://user-images.githubusercontent.com/109722782/190585662-4fcc1e09-ad44-42d8-aff3-49fec86edca0.png)
![image](https://user-images.githubusercontent.com/109722782/190585764-603f376a-ed7b-4d94-b959-d6544fa1d607.png)

Problems also occur when executing./wgd.sh

![LTO9${ RX46$C%US(CC20R](https://user-images.githubusercontent.com/109722782/190585966-1bdd989e-ac2e-4c2b-b6e1-d104d230ef42.png)

**Comment by JiaoXianjun** [comment]
We need more info to debug. Could you fill the info according to the issue template?
