### ISSUE TITLE
About command of "fftgen"

### ISSUE THREAD

**Issue by qgzboy** [open-sdr/openwifi#221]
Hi~
Thanks Mr.Jiao in advanced.
I am using ADRV9361Z7035.
I want to make sure about how to execute command of "./fftgen -v -i -d ../../ifft64 -f 64 -1 -k 1 -p 12 -n 16 -m 16",such as compile enviroment etc.

**Comment by mmehari** [comment]
It is the open source ifft64 generator from openofdm_tx core.
https://github.com/open-sdr/openwifi-hw/blob/master/ip/openofdm_tx/src/ifftmain.v#L37

The repository is located at
https://github.com/ZipCPU/dblclockfft

and you can read a blog post about the core here
https://zipcpu.com/dsp/2018/10/02/fft.html

Hope this helps
