### ISSUE TITLE
咨询两块antsdr开发板相互连接时遇到的问题，仅用RX接RX或是仅TX接TX，两板子竟可以连上并进行通信，令人费解

### ISSUE THREAD

**Issue by NTUGY** [open-sdr/openwifi#231]
焦博士你好，我们遇到了以下问题
1、两块openwifi开发板分别做AP和STA,，用iperf测丢包率和带宽，发现丢包率高达20%，且用无线连接的时候，两者通信距离极近，仅50cm左右AP和STA就要断开连接；
2、在测试的过程中，我们偶然发现，若用同轴电缆将AP和STA的RX和TX交叉相接（AP的RX接STA的TX、AP的TX接STA的RX），两者是无法连接认证成功的，但奇怪的是，使用同轴电缆仅将AP和STA的RX相连或是仅将两者的TX相连，AP和STA可以连接成功并进行通信；
3、将AP的RX接到频谱仪，可以看到带宽为25M左右的频谱，信号峰值功率-68dBm，不像是频谱泄露

**Comment by JiaoXianjun** [comment]
Hello,

Thanks for the feedback. Would you please raise your question in English?

To reproduce, we need more detailed information. Such as Image/Version/Command you have used.

**Comment by NTUGY** [comment]
Okay, Dr Jiao
