### ISSUE TITLE
If openWiFi is started with SD card, how to use the Ila core of vivado to debug the PL signal, or how to debug the PL signal

### ISSUE THREAD

**Issue by zhuzhineng** [open-sdr/openwifi#233]
If openWiFi is started with SD card, how to use the Ila core of vivado to debug the PL signal, or how to debug the PL signal

**Comment by NTUGY** [comment]
Add ILAs to the HW-Design #39

**Comment by JiaoXianjun** [comment]
> Add ILAs to the HW-Design #39

You mean this: https://github.com/open-sdr/openwifi-hw/issues/39 ?

**Comment by NTUGY** [comment]
> > Add ILAs to the HW-Design #39
> 
> You mean this: [open-sdr/openwifi-hw#39](https://github.com/open-sdr/openwifi-hw/issues/39) ?
Yes
