### ISSUE TITLE
Openwifi tx rate debug

### ISSUE THREAD

**Issue by xueduanyue** [open-sdr/openwifi#238]
Hello everyone,

I build openwifi by the last default img. (zedboard_fmcs2)
And I debug tx information.
By using iperf test, I see that the output (tx debug) in dmesg includes RC8 and 585M.
In the doc, RC8 means VHT_MCS in mac80211_rate_control_flags (mac80211.h).
And I try to modify the rate by
./sdrctl dev sdr0 set reg drv_tx 1 9
It works,and dmesg outputs RC8 and 520M.
So the RC8 means HT? Or where is a mistake？

**Comment by JiaoXianjun** [comment]
I need to check the code.

Could you find out the printing source code in sdr.c to understand the meaning of RC?
