### ISSUE TITLE
Kernel Crash Oops During Iperf tests

### ISSUE THREAD

**Issue by rookiebeotch** [open-sdr/openwifi#239]
0. Could you send email to xianjun.jiao@ugent.be to introduce your self?

1. Our image is used directly or you build your own image?
your image directly.
2. What is your own modification?
no modification. only doing ap to client tests in iperf
3. Versions: OS, Vivado, openwifi/openwifi-hw repo branch and commit revision
openwifi-1.3.1-wilsele-1-32bit.img
4. Board/hardware type
zedboard with AD-FMCOMMS4-EBZ
5. WiFi channel number
44 in 5G
6. Steps to reproduce the issue, and the related error message, screenshot, etc
Here is the kernel dump from serial uart.
Unable to handle kernel paging request at virtual address 00711097
pgd = c0004000
[00711097] *pgd=00000000
Internal error: Oops: 5 [#1] PREEMPT SMP ARM
Modules linked in: 8021q arc4 sdr(O) xpu(O) openofdm_rx(O) openofdm_tx(O) rx_intf(O) tx_intf(O) mac80211 cfg80211 xilinx_dma ad9361_drv ipv6
CPU: 0 PID: 0 Comm: swapper/0 Tainted: G           O    4.14.0-gb6e379910a11-dirty #5
Hardware name: Xilinx Zynq Platform
task: c0c0dac0 task.stack: c0c00000
PC is at netif_skb_features+0x1c4/0x394
LR is at 0xcf5d7f40
pc : [<c05f94d0>]    lr : [<cf5d7f40>]    psr: 200f0113
sp : c0c01c40  ip : 00000000  fp : 00000000
r10: d6b44a50  r9 : d4f34000  r8 : 00000000
r7 : 00000000  r6 : 00000014  r5 : 00000000  r4 : 00006000
r3 : 00000000  r2 : 00000000  r1 : 00711097  r0 : d4f34000
Flags: nzCv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment none
Control: 18c5387d  Table: 15dac04a  DAC: 00000051
Process swapper/0 (pid: 0, stack limit = 0xc0c00210)
Stack: (0xc0c01c40 to 0xc0c02000)
1c40: d4f34000 00000000 00000003 df757f00 00000000 d4f34000 d4f34000 00000000
1c60: d4f34000 c05f96b4 d4f344c0 d4f10460 00000000 00000000 d4f34000 d4f34000
1c80: 00000000 d5fd4a00 d6b44a50 c05f99a8 d5fd4a00 df757f00 d4f34000 d6b44a00
1ca0: 00000001 c061f460 df757f00 00000010 df757f00 d6b44a00 d4f34000 00000000
1cc0: 00000000 c05f9fa4 d6b44a50 00000001 c0c01e1c 00000001 fffffff4 00000000
1ce0: 00000000 d4f344c0 c0c01e1c 00000000 d4f10460 df757f00 cf5d7954 c0c01da8
1d00: 01080020 bf1157e0 00000080 00000000 00000000 00000000 c0c02d00 fff053f8
1d20: 000fac01 0a002000 d4f34000 df757f00 00000000 00000000 c0c0534c c015fa38
1d40: d69a3bb8 df757f00 0002c2ec d69a3b80 00000032 d69a3bb8 dfb8d4c0 c016e208
1d60: f8f0010c c0c01e1c df757f00 c0c01da8 d69a3b80 000007d3 d4f344c0 d69a3b88
1d80: fffffff3 bf1176dc 00000000 c010c20c 00000001 df757f00 d4f10460 000005fc
1da0: df757f00 d4f10460 d5fd2780 d6b70e40 0000000f 00000004 00000000 df757f00
1dc0: d4f10460 00000000 c0c01e1c cf5d7940 ffffffe8 00000008 40000006 bf118eb0
1de0: 00000001 00000000 73450e22 00000000 00000001 00000001 00000000 00000000
1e00: 00000000 00000000 00000000 d4f10460 d4f11fe4 bf1c0000 bf1bce98 00000000
1e20: df757f00 d4f10460 d4f344c0 df6ff800 00000000 00000000 00000000 00000000
1e40: 00000000 00000000 00000000 df757f00 d4f10888 d4f10460 bf14d938 bf14d990
1e60: d4f10898 c0c02080 40000006 bf0f4700 d4f10874 d4f10878 00000000 c0c5b4c0
1e80: c0b41294 ffffe000 c0c02080 c0120fb4 00000000 00000006 ffffe000 c0c02098
1ea0: c0c02080 00000101 c0c02080 c0101548 c0c0534c 00000000 df403600 c0b412f8
1ec0: c0c5b4c0 0000000a 0002c2e2 c0c02d00 c0801858 00200102 df56dd64 c0b48280
1ee0: 00000032 00000000 00000000 df403600 f8f01100 00000000 00000000 c01213cc
1f00: c0b48280 c015bc08 c0c05344 c0c1a154 f8f0010c f8f00100 c0c01f40 c0101424
1f20: c0108484 600f0013 ffffffff c0c01f74 c0c54fe0 c0c00000 00000000 c010c20c
1f40: 00000001 00000000 00000001 c01179e0 ffffe000 c0c050f4 c0c050a8 c0b47a48
1f60: c0c54fe0 00000000 00000000 00000000 1f048000 c0c01f90 c0108480 c0108484
1f80: 600f0013 ffffffff 00000051 00000000 ffffe000 c0150e14 000000be c0c5ab80
1fa0: c0c05080 ffffffff c0c5ab80 dffffd80 c0b35a30 c0151148 c0c5abcc c0b00c6c
1fc0: ffffffff ffffffff 00000000 c0b00680 00000000 c0b35a30 c0c5ae14 c0c05098
1fe0: c0b35a2c c0c0ed44 0000406a 413fc090 00000000 0000807c 00000000 00000000
[<c05f94d0>] (netif_skb_features) from [<c05f96b4>] (validate_xmit_skb+0x14/0x2d4)
[<c05f96b4>] (validate_xmit_skb) from [<c05f99a8>] (validate_xmit_skb_list+0x34/0x5c)
[<c05f99a8>] (validate_xmit_skb_list) from [<c061f460>] (sch_direct_xmit+0x104/0x190)
[<c061f460>] (sch_direct_xmit) from [<c05f9fa4>] (__dev_queue_xmit+0x3cc/0x514)
[<c05f9fa4>] (__dev_queue_xmit) from [<bf1157e0>] (ieee80211_rx_handlers+0xd94/0x25e0 [mac80211])
[<bf1157e0>] (ieee80211_rx_handlers [mac80211]) from [<bf1176dc>] (ieee80211_prepare_and_rx_handle+0x2a4/0x10c8 [mac80211])
[<bf1176dc>] (ieee80211_prepare_and_rx_handle [mac80211]) from [<bf118eb0>] (ieee80211_rx_napi+0x9b0/0xa34 [mac80211])
[<bf118eb0>] (ieee80211_rx_napi [mac80211]) from [<bf0f4700>] (ieee80211_tasklet_handler+0xb4/0xd4 [mac80211])
[<bf0f4700>] (ieee80211_tasklet_handler [mac80211]) from [<c0120fb4>] (tasklet_action+0x7c/0x118)
[<c0120fb4>] (tasklet_action) from [<c0101548>] (__do_softirq+0xe0/0x248)
[<c0101548>] (__do_softirq) from [<c01213cc>] (irq_exit+0xd0/0xd4)
[<c01213cc>] (irq_exit) from [<c015bc08>] (__handle_domain_irq+0x60/0xb4)
[<c015bc08>] (__handle_domain_irq) from [<c0101424>] (gic_handle_irq+0x4c/0x90)
[<c0101424>] (gic_handle_irq) from [<c010c20c>] (__irq_svc+0x6c/0xa8)
Exception stack(0xc0c01f40 to 0xc0c01f88)
1f40: 00000001 00000000 00000001 c01179e0 ffffe000 c0c050f4 c0c050a8 c0b47a48
1f60: c0c54fe0 00000000 00000000 00000000 1f048000 c0c01f90 c0108480 c0108484
1f80: 600f0013 ffffffff
[<c010c20c>] (__irq_svc) from [<c0108484>] (arch_cpu_idle+0x38/0x3c)
[<c0108484>] (arch_cpu_idle) from [<c0150e14>] (do_idle+0x16c/0x1f8)
[<c0150e14>] (do_idle) from [<c0151148>] (cpu_startup_entry+0x18/0x1c)
[<c0151148>] (cpu_startup_entry) from [<c0b00c6c>] (start_kernel+0x394/0x3a0)
Code: e5de6002 e156000c 0a000012 e59e102c (e5913000) 
---[ end trace fc4e7ed2fb9f4325 ]---
Kernel panic - not syncing: Fatal exception in interrupt
CPU1: stopping
CPU: 1 PID: 0 Comm: swapper/1 Tainted: G      D    O    4.14.0-gb6e379910a11-dirty #5
Hardware name: Xilinx Zynq Platform
[<c010edbc>] (unwind_backtrace) from [<c010b6f4>] (show_stack+0x10/0x14)
[<c010b6f4>] (show_stack) from [<c06f11c4>] (dump_stack+0x8c/0xa0)
[<c06f11c4>] (dump_stack) from [<c010d4dc>] (ipi_cpu_stop+0x64/0x74)
[<c010d4dc>] (ipi_cpu_stop) from [<c010dc1c>] (handle_IPI+0x6c/0x7c)
[<c010dc1c>] (handle_IPI) from [<c0101464>] (gic_handle_irq+0x8c/0x90)
[<c0101464>] (gic_handle_irq) from [<c010c20c>] (__irq_svc+0x6c/0xa8)
Exception stack(0xdf45bf78 to 0xdf45bfc0)
bf60:                                                       00000001 00000000
bf80: 00000001 c01179e0 ffffe000 c0c050f4 c0c050a8 c0b47a48 c0c54fe0 00000000
bfa0: 00000000 00000000 1f058000 df45bfc8 c0108480 c0108484 60000013 ffffffff
[<c010c20c>] (__irq_svc) from [<c0108484>] (arch_cpu_idle+0x38/0x3c)
[<c0108484>] (arch_cpu_idle) from [<c0150e14>] (do_idle+0x16c/0x1f8)
[<c0150e14>] (do_idle) from [<c0151148>] (cpu_startup_entry+0x18/0x1c)
[<c0151148>] (cpu_startup_entry) from [<0010174c>] (0x10174c)
---[ end Kernel panic - not syncing: Fatal exception in interrupt

7. Describe your debug efforts by Linux native tools, such as tcpdump and "cat /proc/interrupts"
none
8. Describe your debug efforts by: https://github.com/open-sdr/openwifi/blob/master/doc/README.md#Debug-methods

9. Any other thing we need to know for helping you better? 
was trying to see the performance on zedboard. was running as an AP using scripts wgd.sh 1.
ran iperf in client mode to a laptop connected as a wifi client to zedboard(which is AP).

**Comment by JiaoXianjun** [comment]
Please test with our latest img. There should be no issue.
