### ISSUE TITLE
Could not store information to side_info.txt when capturing CSI

### ISSUE THREAD

**Issue by sgjxu30** [open-sdr/openwifi#248]
I am using zedboard+fmc as the receiver to collect CSI sample, and I am using my laptop MacBook Pro to connect zed board via a gigabit USB 3.0 Ethernet adaptor.

I have followed the instructions on https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/csi.md and have modified the wifi channel to be 36, I also have configured the capture condition to only capture the package from another device of mine.

Now I already have the output like this    
<img width="277" alt="Screenshot 2022-11-10 at 15 24 05" src="https://user-images.githubusercontent.com/116023551/201135324-e9ddda55-ddd8-4836-8211-9c31f248f011.png">

But when I run the following cmd on my computer, I found that there is no data in file side_info.txt, of course there will not show 3 figures showing the run-time freq offset, channel state and constellation form equalizer.    
<img width="508" alt="Screenshot 2022-11-07 at 22 49 44" src="https://user-images.githubusercontent.com/116023551/201135070-1d2e596f-c3c5-4dd2-ae13-87b426f57f94.png">

Here are 2 attempts we have tried to debug.
1. I have changed the macbook to a windows laptop but also use the usb ethernet adaptor, but still there is no data in side_info.txt.
2. I have used anther desktop which have the ethernet port itself and does not need an USB ethernet adaptor. And I can see the run-time information now.  

So we found that may be this problem is caused by the adaptor. But we do not know how this would  affect the result.

Could you figure out what caused this problem, is it caused by the adaptor, and how can I modify the document to solve this?

**Comment by JiaoXianjun** [comment]
We have only used Ubuntu Linux with some native Ethernet port on the computer.
For the rest, we do not know.

**Comment by fklement** [comment]
@sgjxu30 How did you in the end solve the problem?
I have exactly the same configuration as you and encounter the same problems.
Somehow I am not receiving data on port `4000`.

**Comment by sgjxu30** [comment]
> @sgjxu30 How did you in the end solve the problem? I have exactly the same configuration as you and encounter the same problems. Somehow I am not receiving data on port `4000`.

I just changed a computer which has an ethernet port, then I do not need an adaptor which may cause the problem.
