### ISSUE TITLE
How does openwifi run on our own PC?

### ISSUE THREAD

**Issue by yangnsd** [open-sdr/openwifi#249]
0. Could you send email to xianjun.jiao@ugent.be to introduce your self?

1. Our image is used directly or you build your own image?

2. What is your own modification?

3. Versions: OS, Vivado, openwifi/openwifi-hw repo branch and commit revision
    linux mint 20.03  / vivado2018.3 / latest
4. Board/hardware type
    antsdr
5. WiFi channel number

6. Steps to reproduce the issue, and the related error message, screenshot, etc

7. Describe your debug efforts by Linux native tools, such as tcpdump and "cat /proc/interrupts"

8. Describe your debug efforts by: https://github.com/open-sdr/openwifi/blob/master/doc/README.md#Debug-methods

9. Any other thing we need to know for helping you better? 

Hi,Dr. Jiao
How does openwifi run on our own PC?

**Comment by JiaoXianjun** [comment]
I don't understand this question.
