### ISSUE TITLE
Question about dmesg

### ISSUE THREAD

**Issue by xueduanyue** [open-sdr/openwifi#250]
Hello everyone,
I turn on the tx dmesg messages.
After sending packets, I can see openwifi_tx and openwifi_tx_interrupt in dmesg.

But I can only see not much information.
How can I save or print all the tx dmesg  bug information to a file?
Thanks for all help.

**Comment by JiaoXianjun** [comment]
why not just google "how to save dmesg output to file"

**Comment by xueduanyue** [comment]
Although the google was not so smooth, I solved it
