### ISSUE TITLE
The packet loss rate of AP and STA is up to 3.7%，Is this a normal phenomenon？

### ISSUE THREAD

**Issue by NTUGY** [open-sdr/openwifi#251]
0. Could you send email to xianjun.jiao@ugent.be to introduce your self?
I am a student from Chongqing University of Posts and Telecommunications.
1. Our image is used directly or you build your own image?
I use your image directly.
2. What is your own modification?
None.
3. Versions: OS, Vivado, openwifi/openwifi-hw repo branch and commit revision
ubuntu18/Vivado2018.3/master branch 
4. Board/hardware type
Antsdr 
5. WiFi channel number
44
6. Steps to reproduce the issue, and the related error message, screenshot, etc
Two antsdr development boards are used as AP and STA respectively. I use iperf to test packet loss rate and bandwidth between AP and STA. The TX and RX antennas of the two development boards are orthogonal. And the distance between two development boards is 3cm. Packet loss rate is up to 3.7% !!!  Is this a normal phenomenon？
![9{%(L @$D5E3@ABQ)7GSVF6](https://user-images.githubusercontent.com/95688668/201518198-0da5c4db-f6a5-46ea-97fd-9ffd45c42dfe.png)

The command I use is as follows：
STA：iperf -s -p 6100 -u -i 1
AP  :  iperf -c  192.168.13.5 -p 6100 -u -i 1 -t 20 -b 40m

**Comment by NTUGY** [comment]
> 
Hi Dr. Jiao，
However, if the Antsdr development board is used as the AP and the mobile phone is used as the STA, the packet loss rate measured with the iperf is very low, and the packet loss rate is only about 0.3%.

**Comment by NTUGY** [comment]
> Seems OK. It is also environment dependent. You can try to tune the system according to https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/frequent_trick.md

Hi Dr. Jiao，
However, if the Antsdr development board is used as the AP and the mobile phone is used as the STA, the packet loss rate measured with the iperf is very low, and the packet loss rate is only about 0.3%.

**Comment by NTUGY** [comment]
> Seems OK. It is also environment dependent. You can try to tune the system according to https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/frequent_trick.md

I checked RX data statistics and found that many packets were lost due to FCS failure

**Comment by NTUGY** [comment]
Hi Dr. Jiao，
Antsdr is used as AP and STA respectively, and cables are used to connect them. I checked the RX data statistics. I found that many packets were lost due to the failure of FCS, so that data retransmission failed five times. This is the reason for the high packet loss rate. I want to know the reason for the failure of FCS. Is AD9361 not good enough as the front end?
![tx2](https://user-images.githubusercontent.com/95688668/202888889-07bff0be-f4fe-4f99-9da6-2aa89e2f6b8b.png)
![rx2](https://user-images.githubusercontent.com/95688668/202888890-184e55ce-601c-401a-8f28-be76916511db.png)

**Comment by JiaoXianjun** [comment]
Please play with all these parameters: https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/frequent_trick.md

**Comment by NTUGY** [comment]
> Please play with all these parameters: https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/frequent_trick.md
Hi Dr. Jiao，
I carefully read the content of the link you gave me. When I override the Linux automatic control for ht packet, the packet loss rate is close to 0%. But  when I use the Linux rate adaptation algorithm minstrel_ht to set the packet rate/MCS automatically via openwifi_tx() function, the packet loss rate is close to 4%. 

I have another question. 
 ./sdrctl dev sdr0 set reg drv_tx 1 N
Does the command above  only change the data frame rate?Does it affect the management frame and control frame rate?
Do you have any good suggestions？

**Comment by NTUGY** [comment]
> Please play with all these parameters: https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/frequent_trick.md
Hi Dr. Jiao，
I carefully read the content of the link you gave me. When I override the Linux automatic control for ht packet, the packet loss rate is close to 0%. But  when I use the Linux rate adaptation algorithm minstrel_ht to set the packet rate/MCS automatically via openwifi_tx() function, the packet loss rate is close to 4%. 

I have another question. 
 ./sdrctl dev sdr0 set reg drv_tx 1 N
Does the command above  only change the data frame rate?Does it affect the management frame and control frame rate?
Do you have any good suggestions？

**Comment by NTUGY** [comment]
> Please play with all these parameters: https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/frequent_trick.md

Hi Dr. Jiao，
I carefully read the content of the link you gave me. When I override the Linux automatic control for ht packet, the packet loss rate is close to 0%. But  when I use the Linux rate adaptation algorithm minstrel_ht to set the packet rate/MCS automatically via openwifi_tx() function, the packet loss rate is close to 4%. 
I have another question. 
 ./sdrctl dev sdr0 set reg drv_tx 1 N
Does the command above  only change the data frame rate?Does it affect the management frame and control frame rate?
Do you have any good suggestions？

**Comment by JiaoXianjun** [comment]
https://github.com/open-sdr/openwifi/blob/b147dfd1528021e018580b2fbcf1c7ed43239962/driver/sdr.c#L1087
