### ISSUE TITLE
How to obtain rssi of ack frame？

### ISSUE THREAD

**Issue by NTUGY** [open-sdr/openwifi#259]
Hi Dr Jiao,
How can I obtain rssi of ack frame?

**Comment by JiaoXianjun** [comment]
You can create a monitor virtual NIC on top the normal sdr0 NIC on board (check our related APP notes).
Then use tcpdump on board to capture the received packet (include ACK frame) to a file (please search on internet about how to).
Then use wireshark (on your computer) to check the RSSI in the packet log.

You can also see RSSI in our dmesg printing on board. Please check: https://github.com/open-sdr/openwifi/blob/master/doc/README.md#Debug-methods
