### ISSUE TITLE
AP Mode 11n not working

### ISSUE THREAD

**Issue by rookiebeotch** [open-sdr/openwifi#262]
0. Could you send email to xianjun.jiao@ugent.be to introduce your self?

1. Our image is used directly or you build your own image?
direct image 1.3.1
2. What is your own modification?
none
3. Versions: OS, Vivado, openwifi/openwifi-hw repo branch and commit revision
1.3.1 master
4. Board/hardware type
zed board and FCOMMS4
5. WiFi channel number
44
6. Steps to reproduce the issue, and the related error message, screenshot, etc
run wdg.sh
then fosdem.sh

here is config file for hostapd.
-----start config----
interface=sdr0
driver=nl80211
country_code=BE
ssid=openwifi5g
hw_mode=a
#hw_mode=g
#channel=5
channel=44
#supported_rates=60 90 120 180 240 360 480 540
#basic_rates=60 90 120 180
ieee80211n=1
#ht_capab=[SHORT-GI-20]
require_ht=1
#ieee80211d=1
#ieee80211h=1
#wpa=2
#wpa_passphrase=myrabbit
#wpa_key_mgmt=WPA-PSK
logger_syslog=-1
logger_syslog_level=2

-----end config----
7. Describe your debug efforts by Linux native tools, such as tcpdump and "cat /proc/interrupts"
i have spectrum analyzer connected to output of FCOMMS4 board.  The packets are coming out in 11g mode but the configuration file is set for 11n in hostapd.  
the client mode works correctly. I have two zed boards. one ap and one client. 
What is interesting is the client is sending in 11n and the AP is sending in 11g/a.  I can see this on the spectrum analyzer.
8. Describe your debug efforts by: https://github.com/open-sdr/openwifi/blob/master/doc/README.md#Debug-methods

9. Any other thing we need to know for helping you better?

**Comment by JiaoXianjun** [comment]
Even in 11n AP, the beacon is sent in 11g mode. That is normal.
If you really want 11n packet tx, you need to run some traffic from AP to client (like iperf tcp/udp). Or do it via packet injection:
https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/inject_80211.md

**Comment by rookiebeotch** [comment]
oh. ok i will try that.  i didn't think about that.  thanks

jorge
