### ISSUE TITLE
Reducing the minimum plateau length causes problems

### ISSUE THREAD

**Issue by Aaron3219** [open-sdr/openwifi#263]
Hello,

In [this](https://github.com/open-sdr/openwifi/blob/master/doc/README.md#get-and-set-a-parameter) README you write that the minimum plateau length can be adjusted with the command:
```sh
$ sdrctl dev sdr0 set reg rx 3 X
```
Where _X_ is the desired length. This works fine when setting it to _X = 90_ or _X = 80_. However, when reducing it even further to values like _X = 40_ the system does not receive packages any more.

I tested the short preamble detection in a simulation according to [your guide](https://github.com/open-sdr/openwifi-hw#simulate-ip-cores) and determined that the short preamble detection works fine. The LTS is also detected, but I don't understand why the system fails.

I am using a ZedBoard.

**Comment by JiaoXianjun** [comment]
You can caputure I/Q from the air according to https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/iq.md, then feed the I/Q to your simulation to verify what is happening.

You can also try to do I/Q self loop back test while changing the parameters: https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/packet-iq-self-loopback-test.md
