### ISSUE TITLE
Does  openwifi  fulfill the COFDM?

### ISSUE THREAD

**Issue by whalevoy** [open-sdr/openwifi#269]
Hello  Teacher, recently  I am studing the SDR, and is puzzled by the fulfillment of COFDM. I kown that COFDM containes the channel coding and OFDM, and openwifi containes OFDM already. My question is ,does openwifi contain channel coding? and if openwifi containes channel coding,  can we say  that  openwifi fulfill   the  COFDM, thank you.

**Comment by JiaoXianjun** [comment]
Openwifi has convolutional encoder and decoder.
Yes it is cofdm.
