### ISSUE TITLE
replace csma/ca with  tdma in openwifi

### ISSUE THREAD

**Issue by whalevoy** [open-sdr/openwifi#271]
Teacher Jiao ,another question,we will transfer mass data  frequently in our project  , is it necessary that csma/ca is replaced by  tdma in openwifi?  and do you have some suggestion to do that work?

**Comment by JiaoXianjun** [comment]
You need to look at the publications page https://github.com/open-sdr/openwifi/blob/master/doc/publications.md

There are many TDMA related work. You can learn and do it yourself.

For openwifi itself, it is just a standard cams/ca WiFi.

We do have internal openwifi version that runs TDMA, but this is under different commercial/non-opensource license.
