### ISSUE TITLE
Kernel problem with openwifi

### ISSUE THREAD

**Issue by puzhitech** [open-sdr/openwifi#279]
Hello, Dr. Jiao
 when we transplanted our SDR board, we encountered a problem that the kernel could not enter. 
What could be the reason?
Porting is based on the latest version of 2021_r1

Is it convenient for you to transplant openwifi based on our board? 
In addition to the schematic diagram, what files do we need to open the source?

thank you

booting log:

U-Boot 2018.01 (Feb 22 2023 - 17:21:01 -0800) Analog Devices Inc. ADRV9364-Z7020

Model: Analog Devices ADRV9364-Z7020 (Z7020/AD9364)
Board: Xilinx Zynq
Silicon: v3.1
I2C:   ready
DRAM:  ECC disabled 1 GiB
MMC:   sdhci@e0100000: 0 (SD)
SF: Detected w25q256 with page size 256 Bytes, erase size 4 KiB, total 32 MiB
*** Warning - bad CRC, using default environment

In:    serial@e0000000
Out:   serial@e0000000
Err:   serial@e0000000
Net:   No ethernet found.
reading uEnv.txt
407 bytes read in 19 ms (20.5 KiB/s)
Importing environment from SD ...
Hit any key to stop autoboot:  0 
Device: sdhci@e0100000
Manufacturer ID: 3
OEM: 5344
Name: SD32G 
Tran Speed: 50000000
Rd Block Len: 512
SD version 3.0
High Capacity: Yes
Capacity: 29.7 GiB
Bus Width: 4-bit
Erase Group Size: 512 Bytes
reading uEnv.txt
407 bytes read in 18 ms (21.5 KiB/s)
Loaded environment from uEnv.txt
Importing environment from SD ...
Running uenvcmd ...
Copying Linux from SD to RAM...
reading uImage
5593704 bytes read in 328 ms (16.3 MiB/s)
reading devicetree.dtb
18473 bytes read in 25 ms (720.7 KiB/s)
** Unable to read file uramdisk.image.gz **
## Booting kernel from Legacy Image at 03000000 ...
   Image Name:   Linux-5.10.0-98248-g1bbe32fa5182
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    5593640 Bytes = 5.3 MiB
   Load Address: 00008000
   Entry Point:  00008000
   Verifying Checksum ... OK
## Flattened Device Tree blob at 02a00000
   Booting using the fdt blob at 0x2a00000
   Loading Kernel Image ... OK
   Loading Device Tree to 1fff8000, end 1ffff828 ... OK

Starting kernel ...

C:0x000080C0-0x0055DA40->0x010C9800-0x0161F180
Uncompressing Linux... done, booting the kernel.

**Comment by JiaoXianjun** [comment]
Hi,

I am afraid that I could help nothing here. We do the wifi part which is after linux porting is successful. Now seems like your linux porting is not done yet. We do not have much experiences on the linux part.

Some suggestions:
1. You need to be very clear about what is the hardware difference between your board and the ADI/Xilinx reference board. (Which one is your reference? adrv9364z7020? zedboard+fmcomms2?)
2. If there are any hardware differences, you might need to change the devicetree and some kernel configurations to align with those changes you made on top the reference board.
