### ISSUE TITLE
wget openwifi-low-acc.mp4 timeout

### ISSUE THREAD

**Issue by cloud9477** [open-sdr/openwifi#282]
In the update_sdcard.sh, line 141, wget openwifi-low-aac.mp4 no response.

sudo wget -P ./ https://users.ugent.be/~xjiao/openwifi-low-aac.mp4
--2023-03-07 14:49:25--  https://users.ugent.be/~xjiao/openwifi-low-aac.mp4
Resolving users.ugent.be (users.ugent.be)... 157.193.40.145
Connecting to users.ugent.be (users.ugent.be)|157.193.40.145|:443... failed: Connection timed out.
Retrying.

--2023-03-07 14:51:37--  (try: 2)  https://users.ugent.be/~xjiao/openwifi-low-aac.mp4
Connecting to users.ugent.be (users.ugent.be)|157.193.40.145|:443... ^C

**Comment by JiaoXianjun** [comment]
Maybe just a temporary ugent server failure.

Anyway, I just fix it by pointing the video file to a github location. Please check my commit few seconds ago.

Tell me it works or not?

Thanks!

**Comment by cloud9477** [comment]
The github link works.
