### ISSUE TITLE
Windowing function

### ISSUE THREAD

**Issue by peking428** [open-sdr/openwifi#283]
Hello Brother Jiao, 

In our openwifi logic, in the process of moving the time-domain signal to the frequency-domain (Fourier transform) , the time-domain signal is intercepted by a windowing function. What kind of windowing function is used(hanning ? hamming? blackman ? ...)? Can you know the code in which location, we found that the test spectrum leak problem, I looked for a long time did not find, please give us some help~  , thank you!

**Comment by peking428** [comment]
![1678435878882](https://user-images.githubusercontent.com/46754257/224259950-7fb1a965-a468-4233-bbc6-2c6fc4d65c06.png)

**Comment by peking428** [comment]
> 

What kind of windowing function is used(hanning ? hamming? blackman ? ...)? Can you know the code in which location

**Comment by JiaoXianjun** [comment]
We never use any windowing function.

**Comment by peking428** [comment]
ok. thank you ~
