### ISSUE TITLE
How Can I build hdl design in vivado?

### ISSUE THREAD

**Issue by waseem-arshad94** [open-sdr/openwifi#286]
0. Yes, I have been send the email

1.  I am using your image as it is.

2.  I want to modify in hdl design of openwifi. 

3. Versions: OS, Vivado, openwifi/openwifi-hw repo branch and commit revision: windows, vivado 2019.1

4. Board/hardware type: adrv9361z7035-bob

5. WiFi channel number: 1,6 and 11

6. I want to build hdl design in vivado 2019.1

7. Not started debugging 

8. Not started debugging

9.  I need to build the hdl design after that modify it.

**Comment by JiaoXianjun** [comment]
Please read readme of: https://github.com/open-sdr/openwifi-hw
