### ISSUE TITLE
open WiFi communication distance

### ISSUE THREAD

**Issue by zhuzhineng** [open-sdr/openwifi#287]
How much communication distance can be increased by using AD-TRXBOOST1-EBZ power amplifier

**Comment by JiaoXianjun** [comment]
I haven’t tested it.

**Comment by zhuzhineng** [comment]
Well, at present, we have tested antsdr development board, and its communication distance is only about 100 cm. Is there any way to increase its communication distance？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-sdr/openwifi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月30日(星期四) 晚上10:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-sdr/openwifi] open WiFi communication distance (Issue #287)





 
I don't know. Maybe you can check with antsdr manufacture.

**Comment by JiaoXianjun** [comment]
Can you tell more information?
1. Two antsdr? or antsdr to another phone/laptop?
2. channel number you were using
3. 11a/g? Or 11n? (command/traffic you run at both side for test)
4. Our latest img?
5. Antenna type?
6. etc. (More detailed, better).

**Comment by zhuzhineng** [comment]
We use two AntSdrs. The antenna uses the original 9dbi antenna, uses 802.11n, the output frequency is 5.2GHZ, and the channel bandwidth is 20MHZ



---Original---
From: "Jiao ***@***.***&gt;
Date: Thu, Mar 30, 2023 22:50 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-sdr/openwifi] open WiFi communication distance (Issue #287)




 
Can you tell more information?
  
Two antsdr? or antsdr to another phone/laptop?
 
channel number you were using
 
11a/g? Or 11n? (command/traffic you run at both side for test)
 
Our latest img?
 
Antenna type?
 
etc. (More detailed, better).

**Comment by JiaoXianjun** [comment]
You can try different channel/band.
