### ISSUE TITLE
IP routing

### ISSUE THREAD

**Issue by Baraday3** [open-sdr/openwifi#288]
1. Our image is used directly or you build your own image?
Openwifi's image.

3. What is your own modification?
Nothing.

5. Versions: OS, Vivado, openwifi/openwifi-hw repo branch and commit revision
master branch

7. Board/hardware type
ZC706+FMCOMMS4 and ZedBoard+FMCOMMS4

8. WiFi channel number
44

10. Steps to reproduce the issue, and the related error message, screenshot, etc

Dear Sir,

In ad-hoc mode I can communicate between two boards via wireless. I can ping from 192.168.13.1 to 192.168.13.2 or vice versa. Unfortunatelly, If I wanted to ping to 192.168.13.2 I must connect via ssh to board and then I can ping to 192.168.13.2.  
All I want to do is I would like ping from 192.168.10.25 to 192.168.10.57. I have tried ip routing but It didn't work. If you help me I would be very happy.

![connection_diagram](https://user-images.githubusercontent.com/9075262/226630004-b156d6c1-dad2-4654-b432-ff7103154661.PNG)

**Comment by JiaoXianjun** [comment]
IP routing is not part of our work. We rely on the "standard" functionality offered by "standard" Linux distribution (Here it is Raspberry PI OS -- raspbian). You need to search for general purpose Linux networking aspect/help.
