### ISSUE TITLE
DHCP Server fails to start in Access Point Mode

### ISSUE THREAD

**Issue by SteffenFri** [open-sdr/openwifi#289]
Hi,

I followed the last developments of the openwifi project with high interest and tried to start the new release Notter 1.4.0 by using the "zed_fmcs2-board" 
and the "zcu102_fmcs2-board". However, there seems to be a problem with the dhcp server running on the access point, that it failing to start within the fosdem.sh startup script. I checked the dhcpd configs, but they seem fine and I did not change them in the first place. 

Am I missing something?  

I have successfully booted the image and started the script ./wgd.sh to enable the access point.
I get the following output:

```
    usage:
        Script for load (or download+load) different driver and FPGA img without rebooting
        no  argument: Load .ko driver files and FPGA img (if system_top.bit.bin exist) in current dir with test_mode=0.
        1st argument: If it is a NUMBER, it will be assigned to test_mode. Then load everything from current dir.
        1st argument: If it is a string called "remote", it will download driver/FPGA and load everything.
        - 2nd argument (if exist) is the target directory name for downloading and reloading
        - 3rd argument (if exist) is the value for test_mode
        1st argument: neither NUMBER nor "remote" nor a .tar.gz file, it is regarded as a directory and load everything from it.
        - 2nd argument (if exist) is the value for test_mode
        1st argument: a .tar.gz file, it will be unpacked then load from that unpacked directory
        - 2nd argument (if exist) is the value for test_mode
 
    Module                  Size  Used by
    mac80211              565248  0
    libarc4                16384  1 mac80211
    xilinx_dma             28672  0
    ad9361_drv            163840  2
    cfg80211              319488  1 mac80211
    8021q                  24576  0
    ipv6                  397312  28
    TARGET_DIR ./
    DOWNLOAD_FLAG 0
    test_mode 0
    tx_offset_tuning_enable 0
    $TARGET_DIR is found!
 
    hostapd: no process found
    Failed to stop dhcpd.service: Unit dhcpd.service not loaded.
    dhcpd: no process found
    sdr0: ERROR while getting interface flags: No such device
    rmmod: ERROR: Module sdr is not currently loaded
    ./load_fpga_img.sh: line 14: warning: command substitution: ignored null byte in input
    xlnx,zynq-7000
    .//system_top.bit.bin
    system_top.bit.bin
    + ifconfig sdr0 down
    sdr0: ERROR while getting interface flags: No such device
    + rmmod sdr
    rmmod: ERROR: Module sdr is not currently loaded
    + rmmod openofdm_rx
    rmmod: ERROR: Module openofdm_rx is not currently loaded
    + rmmod openofdm_tx
    rmmod: ERROR: Module openofdm_tx is not currently loaded
    + rmmod rx_intf
    rmmod: ERROR: Module rx_intf is not currently loaded
    + rmmod tx_intf
    rmmod: ERROR: Module tx_intf is not currently loaded
    + rmmod xpu
    rmmod: ERROR: Module xpu is not currently loaded
    + sleep 1
    + '[' -f .//system_top.bit.bin ']'
    + echo 0
    + mkdir -p /lib/firmware
    + cp .//system_top.bit.bin /lib/firmware/ -rf
    + echo system_top.bit.bin
    + '[' xlnx,zynq-7000 '!=' xlnx,zynq-7000 ']'
    + SPI_DEVNAME=spi0.0
    + DDS_DEVNAME=79024000.cf-ad9361-dds-core-lpc
    + ADC_DEVNAME=79020000.cf-ad9361-lpc
    + '[' '!' -d /sys/bus/spi/drivers/ad9361/spi0.0 ']'
    + cd /sys/bus/spi/drivers/ad9361/
    + echo spi0.0
    + echo spi0.0
    + '[' '!' -d /sys/bus/platform/drivers/cf_axi_adc/79020000.cf-ad9361-lpc ']'
    + cd /sys/bus/platform/drivers/cf_axi_adc/
    + echo 79020000.cf-ad9361-lpc
    + echo 79020000.cf-ad9361-lpc
    + set +x
    tx_offset_tuning_enable 0
    openwifi_ad9361_fir_tx_0MHz_11n.ftr tx_fir_enable 1
    Found openwifi_ad9361_fir_tx_0MHz_11n.ftr
    + test -f /sys/bus/iio/devices/iio:device0/in_voltage_rf_bandwidth
    + test -f /sys/bus/iio/devices/iio:device1/in_voltage_rf_bandwidth
    + test -f /sys/bus/iio/devices/iio:device2/in_voltage_rf_bandwidth
    + cd /sys/bus/iio/devices/iio:device2/
    + set +x
    FIR Rx: 48,1 Tx: 48,1
    1
    1
    rx0 agc fast_attack
    slow_attack
    fast_attack
    rx1 agc fast_attack
    slow_attack
    fast_attack
    40000000
    25215513
    40000000
    25215414
    rssi
    113.75 dB
    114.00 dB
    rx0 gain to 70
    72.000000 dB
    ./rf_init_11n.sh: 101: echo: echo: I/O error
    72.000000 dB
    rx1 gain to 70
    73.000000 dB
    ./rf_init_11n.sh: 106: echo: echo: I/O error
    73.000000 dB
    tx0 gain -89dB
    -10.000000 dB
    -89.000000 dB
    tx1 gain 0dB
    -10.000000 dB
    0.000000 dB
    rmmod: ERROR: Module tx_intf is not currently loaded
    + insmod .//tx_intf.ko
    tx_intf is loaded!
    rmmod: ERROR: Module rx_intf is not currently loaded
    + insmod .//rx_intf.ko
    rx_intf is loaded!
    rmmod: ERROR: Module openofdm_tx is not currently loaded
    + insmod .//openofdm_tx.ko
    openofdm_tx is loaded!
    rmmod: ERROR: Module openofdm_rx is not currently loaded
    + insmod .//openofdm_rx.ko
    openofdm_rx is loaded!
    rmmod: ERROR: Module xpu is not currently loaded
    + insmod .//xpu.ko
    xpu is loaded!
    rmmod: ERROR: Module sdr is not currently loaded
    + insmod .//sdr.ko test_mode=0
    sdr is loaded!
    the end
```

After starting the file "./fosdem.sh" I get the following output:
```
    hostapd: no process found
    rm: cannot remove '/var/run/dhcpd.pid': No such file or directory
    Job for isc-dhcp-server.service failed because the control process exited with error code.
    See "systemctl status isc-dhcp-server.service" and "journalctl -xe" for details.
    Configuration file: hostapd-openwifi.conf
    sdr0: interface state UNINITIALIZED->COUNTRY_UPDATE
    Using interface sdr0 with hwaddr a2:02:d6:13:6b:17 and ssid "openwifi"
    sdr0: interface state COUNTRY_UPDATE->ENABLED
    sdr0: AP-ENABLED
```
The access point has ssucessfully started, the interface "sdr0" is up and the openwifi is visible for other devices but it is not possible to connect to the access point and ip-adress via DHCP.

After executing the command "systemctl status isc-dhcp-server.service" I get the following output:

```
    ● isc-dhcp-server.service - LSB: DHCP server
        Loaded: loaded (/etc/init.d/isc-dhcp-server; generated)
        Active: failed (Result: exit-code) since Tue 2023-03-21 14:01:44 GMT; 6min ago
            Docs: man:systemd-sysv-generator(8)
        Process: 25118 ExecStart=/etc/init.d/isc-dhcp-server start (code=exited, status=1/FAILURE)
            CPU: 357ms
        CGroup: /system.slice/isc-dhcp-server.service
                └─25136 /usr/sbin/dhcpd -4 -q -cf /etc/dhcp/dhcpd.conf

    Mar 21 14:01:44 analog isc-dhcp-server[25209]:  failed!
    Mar 21 14:01:44 analog systemd[1]: isc-dhcp-server.service: Control process exited, code=exited, status=1/FAILURE
    Mar 21 14:01:44 analog systemd[1]: isc-dhcp-server.service: Failed with result 'exit-code'.
    Mar 21 14:01:44 analog systemd[1]: isc-dhcp-server.service: Unit process 25136 (dhcpd) remains running after unit stopped.
    Mar 21 14:01:44 analog systemd[1]: Failed to start LSB: DHCP server.
    Mar 21 14:01:44 analog dhcpd[25136]: receive_packet failed on sdr0: Network is down
    Mar 21 14:01:46 analog dhcpd[25136]: DHCPDISCOVER from a2:02:d6:13:6b:17 via sdr0
    Mar 21 14:01:47 analog dhcpd[25136]: DHCPOFFER on 192.168.13.6 to a2:02:d6:13:6b:17 (analog) via sdr0
    Mar 21 14:01:47 analog dhcpd[25136]: DHCPREQUEST for 192.168.13.6 (192.168.13.1) from a2:02:d6:13:6b:17 (analog) via sdr0
    Mar 21 14:01:47 analog dhcpd[25136]: DHCPACK on 192.168.13.6 to a2:02:d6:13:6b:17 (analog) via sdr0
```

**Comment by JiaoXianjun** [comment]
That dhcp failure won't affect the system. You can live with it as long as your client can get IP from openwifi AP.

https://github.com/open-sdr/openwifi/blob/master/doc/known_issue/notter.md

**Comment by JiaoXianjun** [comment]
Did you try the method in the known issue page? (The link I gave).
Are you using the official zed/zcu102 and ADI fmcomms board?
When did you download the img? We updated recently. Maybe you can download again?
We don't have ip fetching issue on zed/zcu102 + fmcomms board.

**Comment by JiaoXianjun** [comment]
Do you still have the dhcp issue?

**Comment by SteffenFri** [comment]
Yes, I have tried the method on your known issue page where I have restarted the dhcp-server and tried to connect the client again. 
While I a trying to connect the client to the AP by executing the command " wpa_supplicant -i sdr0 -c wpa-openwifi.conf " at the client I will get the following output for the client:
´´
Successfully initialized wpa_supplicant
nl80211: kernel reports: Match already configured
nl80211: kernel reports: Match already configured
nl80211: kernel reports: Match already configured
nl80211: kernel reports: Match already configured
nl80211: kernel reports: Match already configured
nl80211: kernel reports: Match already configured
nl80211: kernel reports: Match already configured
nl80211: kernel reports: Match already configured
nl80211: kernel reports: Match already configured
nl80211: kernel reports: Match already configured
nl80211: kernel reports: Match already configured
nl80211: kernel reports: Match already configured
nl80211: kernel reports: Match already configured
nl80211: kernel reports: Match already configured
nl80211: kernel reports: Match already configured
nl80211: kernel reports: Match already configured
nl80211: kernel reports: Match already configured
nl80211: kernel reports: Match already configured
nl80211: kernel reports: Match already configured
nl80211: kernel reports: Match already configured
nl80211: kernel reports: Match already configured
nl80211: kernel reports: Match already configured
sdr0: SME: Trying to authenticate with 52:aa:69:c1:c3:79 (SSID='openwifi' freq=5220 MHz)
sdr0: Trying to associate with 52:aa:69:c1:c3:79 (SSID='openwifi' freq=5220 MHz)
sdr0: Associated with 52:aa:69:c1:c3:79
sdr0: CTRL-EVENT-CONNECTED - Connection to 52:aa:69:c1:c3:79 completed [id=0 id_str=]
sdr0: CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
^Csdr0: CTRL-EVENT-DISCONNECTED bssid=52:aa:69:c1:c3:79 reason=3 locally_generated=1
nl80211: deinit ifname=sdr0 disabled_11b_rates=0
sdr0: CTRL-EVENT-TERMINATING 
´´
At the access point I will get the following output:

``
sdr0: STA 2a:1c:47:ad:f9:ac IEEE 802.11: authenticated
sdr0: STA 2a:1c:47:ad:f9:ac IEEE 802.11: associated (aid 1)
sdr0: AP-STA-CONNECTED 2a:1c:47:ad:f9:ac
sdr0: STA 2a:1c:47:ad:f9:ac RADIUS: starting accounting session 6FA675B3DFB6CD1B
sdr0: AP-STA-DISCONNECTED 2a:1c:47:ad:f9:ac
sdr0: INTERFACE-DISABLED 
sdr0: INTERFACE-ENABLED 
handle_probe_req: send failed
handle_probe_req: send failed
handle_probe_req: send failed
handle_probe_req: send failed
handle_probe_req: send failed
handle_probe_req: send failed
handle_probe_req: send failed
handle_probe_req: send failed
handle_probe_req: send failed
handle_probe_req: send failed
handle_probe_req: send failed
handle_probe_req: send failed
 ``   
When I try to connect the client by executing the command   " iwconfig sdr0 essid openwifi "   I will get the following output  at the access point :
``
sdr0: STA 7e:04:66:10:7d:63 IEEE 802.11: authenticated
sdr0: STA 7e:04:66:10:7d:63 IEEE 802.11: associated (aid 1)
sdr0: AP-STA-CONNECTED 7e:04:66:10:7d:63
sdr0: STA 7e:04:66:10:7d:63 RADIUS: starting accounting session 38161E73D463CDFD
sdr0: AP-STA-DISCONNECTED 7e:04:66:10:7d:63
```
There is no additional  output  at the client.

After trying to connect the client by executing the commands "wpa_supplicant -i sdr0 -c wpa-openwifi.conf" or "iwconfig sdr0 essid openwifi" I have used the command "dhclient sdr0" to get an  ip address from the access point. This command terminates after a timeout without additional command line output.

**Comment by JiaoXianjun** [comment]
Can you use cellphone or computer to act as client?

While you use wpa_supplicant on client, could you please update your onboard file:
https://github.com/open-sdr/openwifi/blob/master/user_space/hostapd-openwifi.conf
remove following password settings from it:
```
wpa=1
wpa_passphrase=openwifi
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP CCMP
wpa_ptk_rekey=600
```

**Comment by SteffenFri** [comment]
For me it was possible to connect my smartphone and my computer.

The settings you have mentioned from "hostapd-openwifi.conf " are already commented.

**Comment by JiaoXianjun** [comment]
please follow this. https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/ap-client-two-sdr.md

Did you run dhclient?
