### ISSUE TITLE
Questions about Ad-Hoc Mode

### ISSUE THREAD

**Issue by Baraday3** [open-sdr/openwifi#292]
0. Could you send email to xianjun.jiao@ugent.be to introduce your self? Sent earlier

1. Our image is used directly or you build your own image? Latest Image by openwifi

2. What is your own modification? nothing

3. Versions: OS, Vivado, openwifi/openwifi-hw repo branch and commit revision master branch, 2021.1 vivado, ubuntu 18

4. Board/hardware type Zedboard+fmcomms4 and ZC706+fmcomms4

5. WiFi channel number 44

Hello,

I have two boards. They are working in ad-hoc mode. I have three questions for ad-hoc mode.

1) Unfortunately, data rate is very low. It is around 1 to 2 Mbps. I have tried to override minstrel_ht and non-ht packet values but nothing changed. I also connected two board with cables. Nothing changed. What can I do to improve data rate?

2) How can I enable WPA for ad-hoc mode?

3) Is it possible to change modulations? Can I change MCS values? If so how can I do ?

Thank you for helping.

**Comment by JiaoXianjun** [comment]
https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/frequent_trick.md
