### ISSUE TITLE
Add support for header files in user space

### ISSUE THREAD

**Issue by lng205** [open-sdr/openwifi#295]
Hello,

I am currently attempting to install a serial port driver onto my board, but I have encountered an issue indicating that there is no kernel header file in user space. While researching this problem, I came across a similar issue on ADI's engineer zone at the following link:

https://ez.analog.com/linux-software-drivers/f/q-a/565120/kuiper-kernel-version-number-causing-module-loading-and-compiling-issues

Perhaps the project could benefit from adding the necessary header file to the image or modifying the prepare_kernel.sh script?

**Comment by JiaoXianjun** [comment]
The board OS is from raspberry pi, so you can install anything you want via "apt" command on board. Will this way work?

Or, could you come up with a pull request?

**Comment by lng205** [comment]
Thank you for your response. The 'apt' command has been useful, but unfortunately, I couldn't find the driver I need on the list. As a student, I'm not very familiar with Linux, but I believe this issue could affect anyone who wants to compile a C file on board.
If my solution proves effective, I will submit a pull request.

**Comment by lng205** [comment]
After editing the /kernel_boot/kernel_config file and enabling the driver, I successfully solved my problem by recompiling and substituting the kernel. However, the issue of the missing kernel header files still persists, which could potentially impact other developers as well.
