### ISSUE TITLE
file system corruption

### ISSUE THREAD

**Issue by xiaoshanzi** [open-sdr/openwifi#296]
I followed the "Build openwifi Linux img from scratc" operation, and an EXIT-fs error occurred when executing "./pos_config.sh", which caused many libraries and tools to fail to download and install.
It was found that the file system was damaged. After repeated steps, it was found that this problem would occur as long as apt-get -y install was used.
![2023-04-06 19-13-02屏幕截图](https://user-images.githubusercontent.com/7878312/230364009-a09d6637-bd08-44db-a04c-f57718b4f63f.png)

**Comment by JiaoXianjun** [comment]
Please offer more detailed context (such as those questions in our issue template), not just the error itself. You could give the step by step operations (and their outputs), that leads to this error, beginning from the scratch (such as, from "git clone").
