### ISSUE TITLE
CSI defuzzed

### ISSUE THREAD

**Issue by mkk0719** [open-sdr/openwifi#298]
Hi
Thank you very much for providing this project. I want to defuzz CSI and I have studied these two paper:
https://dl.acm.org/doi/abs/10.1145/3448300.3468255
https://github.com/open-sdr/openwifi-hw-img/raw/master/doc_repo/Seppe_Dejonckheere_masterproef.pdf
The paper mentioned that there is an unknown factor which will casue the difference between the prediction and the observed effects. I have used the learning based method(mentiond in the second paper) and defuzz the special parament of fuzzing successfully, but I can't use the same defuzz parttern to defuzz other fuzzed CSI which was fuzzed by other paraments. Is there anything wrong or it just can't deal with this problem?
I actually want to change the fuzzed parameter dynamically and be able to defuzz it on the receiver.
Can you give me some advice?

**Comment by JiaoXianjun** [comment]
https://github.com/open-sdr/openwifi/issues/285
