### ISSUE TITLE
Modify the frequency

### ISSUE THREAD

**Issue by xiaoshanzi** [open-sdr/openwifi#299]
I need to modify the frequency to 2.4G,Change the "channel" parameter in the "hostapd-openwifi.conf" file to 11,But it failed,report“sdr0: IEEE 802.11 Configured channel (11) not found from the channel list of current mode (2) IEEE 802.11a”。

![2023-04-11 15-09-23屏幕截图](https://user-images.githubusercontent.com/7878312/231083437-8bdb9c84-ac1c-4466-bd57-88915fa22877.png)

**Comment by JiaoXianjun** [comment]
please use 802.11g instead of a in the configuration file.
