### ISSUE TITLE
Questions about WPA

### ISSUE THREAD

**Issue by xueduanyue** [open-sdr/openwifi#300]
Can Openwifi turn off the wireless encryption function？
It seems to be a certain WPA algorithm.
My img version is 1.4.0 and the board_name is zed_fmcs2.

**Comment by JiaoXianjun** [comment]
You can use this one to replace the hostapd configuration file on board:
https://github.com/open-sdr/openwifi/blob/master/user_space/hostapd-openwifi.conf

**Comment by xueduanyue** [comment]
Very thankful！
