### ISSUE TITLE
The output power of antsdr development board

### ISSUE THREAD

**Issue by zhuzhineng** [open-sdr/openwifi#302]
Hello, what is the output power of antsdr development board without antenna? We tested the output power using a signal analyzer and the result was only -12dBm. Our test process is to use a coaxial cable to link the board TX and signal analyzer input, and then by calculating the signal bandwidth/resolution bandwidth to take logarithm multiplied by 10, plus the power displayed on the signal analyzer.

**Comment by JiaoXianjun** [comment]
Seems normal to me.
