### ISSUE TITLE
Channel sweeping with openwifi 

### ISSUE THREAD

**Issue by haochenku** [open-sdr/openwifi#308]
Hi all,
   One quick question, does the current openWi-Fi support channel sweeping and fetching CSI? 

regards

**Comment by JiaoXianjun** [comment]
yes it supports

**Comment by haochenku** [comment]
Cool, could you point to us the setup or is there any example?

**Comment by JiaoXianjun** [comment]
search csi in this page

https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/README.md
