### ISSUE TITLE
Question about uboot

### ISSUE THREAD

**Issue by lydenlau** [open-sdr/openwifi#322]
Hello, Dr. Jiao:

I'm trying to transplant OpenWiFi to my own board (7045+fmcs2).

In openwifi/kernel_boot,Each board has independent u-boot.elf

I compiled using the method provided by xilinx (https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/18841973/Build+U-Boot), but it doesn't work.

I would like to know how you compiled it. 

Thanks a lot！

**Comment by JiaoXianjun** [comment]
I do not remember that I compile it. I copy it from ADI original SD card.
