### ISSUE TITLE
Openwifi in ADRV9361z7035 shut down

### ISSUE THREAD

**Issue by frigo125** [open-sdr/openwifi#323]
0. Could you send email to xianjun.jiao@ugent.be to introduce your self?
sent
1. Our image is used directly or you build your own image?
your image
2. What is your own modification?
none
3. Versions: OS, Vivado, openwifi/openwifi-hw repo branch and commit revision
Ubuntu 18.04, Vivado 2021.1, master branch,
4. Board/hardware type
adrv9361z7035
5. WiFi channel number
1
6. Steps to reproduce the issue, and the related error message, screenshot, etc

Hello DR.JIAO, 
We used adrv9361z7035 to implement Openwifi, according to your Quick start, we flash the image to a SD card, and copy  the files in BOOT/openwifi/adrv9361z7035 to BOOT, and insert my SD card into Board and power on, Linux was started normally. when Linux startup is finish. we can login and see root@analog:~# , about 6 seconds, the system shut down, and we can't do anything , (for example, cd openwifi ), and green/yellow leds are still illume. 
![屏幕截图 2023-07-10 233829](https://github.com/open-sdr/openwifi/assets/139147915/f977142d-ee57-45c0-9a17-04ef5777410d)

**Comment by JiaoXianjun** [comment]
1. Could save the dmesg output right after its booting? (before freezing)
2. Could you make sure use our latest img? (old img's devicetree could cause this issue)
3. Could you try different SD card flashing tool under different OS?

**Comment by frigo125** [comment]
1，I save the dmesg output before freezing.
root@analog:~# dmesg
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 5.10.0-98248-g1bbe32fa5182-dirty (jxj@jxj-pc) (arm-xilinx-linux-gnueabi-gcc.real (GCC) 10.2.0, GNU ld (GNU Binutils) 2.35.0.20200730) #6 SMP PREEMPT Tue Mar 14 12:13:23 CET 2023
[    0.000000] CPU: ARMv7 Processor [413fc090] revision 0 (ARMv7), cr=18c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt: Machine model: Analog Devices ADRV9361-Z7035 (Z7035/AD9361)
[    0.000000] OF: fdt: earlycon: stdout-path /amba@0/uart@E0001000 not found
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] cma: Reserved 128 MiB at 0x16800000
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x000000001fffffff]
[    0.000000]   HighMem  empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x000000001fffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x000000001fffffff]
[    0.000000] On node 0 totalpages: 131072
[    0.000000]   Normal zone: 1024 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 131072 pages, LIFO batch:31
[    0.000000] percpu: Embedded 15 pages/cpu s29900 r8192 d23348 u61440
[    0.000000] pcpu-alloc: s29900 r8192 d23348 u61440 alloc=15*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 130048
[    0.000000] Kernel command line: console=ttyPS0,115200 root=/dev/mmcblk0p2 rw earlycon rootfstype=ext4 rootwait clk_ignore_unused cpuidle.off=1
[    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 371432K/524288K available (8192K kernel code, 803K rwdata, 5732K rodata, 1024K init, 151K bss, 21784K reserved, 131072K cma-reserved, 0K highmem)
[    0.000000] rcu: Preemptible hierarchical RCU implementation.
[    0.000000] rcu:     RCU restricting CPUs from NR_CPUS=4 to nr_cpu_ids=2.
[    0.000000]  Trampoline variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=2
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] efuse mapped to (ptrval)
[    0.000000] slcr mapped to (ptrval)
[    0.000000] L2C: platform modifies aux control register: 0x72360000 -> 0x72760000
[    0.000000] L2C: DT/platform modifies aux control register: 0x72360000 -> 0x72760000
[    0.000000] L2C-310 erratum 769419 enabled
[    0.000000] L2C-310 enabling early BRESP for Cortex-A9
[    0.000000] L2C-310 full line of zeros enabled for Cortex-A9
[    0.000000] L2C-310 ID prefetch enabled, offset 1 lines
[    0.000000] L2C-310 dynamic clock gating enabled, standby mode enabled
[    0.000000] L2C-310 cache controller enabled, 8 ways, 512 kB
[    0.000000] L2C-310: CACHE_ID 0x410000c8, AUX_CTRL 0x76760001
[    0.000000] random: get_random_bytes called from start_kernel+0x33c/0x4dc with crng_init=0
[    0.000000] zynq_clock_init: clkc starts at (ptrval)
[    0.000000] Zynq clock init
[    0.000009] sched_clock: 64 bits at 333MHz, resolution 3ns, wraps every 4398046511103ns
[    0.000029] clocksource: arm_global_timer: mask: 0xffffffffffffffff max_cycles: 0x4ce07af025, max_idle_ns: 440795209040 ns
[    0.000054] Switching to timer-based delay loop, resolution 3ns
[    0.000145] clocksource: ttc_clocksource: mask: 0xffff max_cycles: 0xffff, max_idle_ns: 537538477 ns
[    0.000182] timer #0 at (ptrval), irq=25
[    0.000728] Console: colour dummy device 80x30
[    0.000757] Calibrating delay loop (skipped), value calculated using timer frequency.. 666.66 BogoMIPS (lpj=3333333)
[    0.000774] pid_max: default: 32768 minimum: 301
[    0.000951] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.000964] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.001601] CPU: Testing write buffer coherency: ok
[    0.001636] CPU0: Spectre v2: using BPIALL workaround
[    0.001801] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.002306] Setting up static identity map for 0x100000 - 0x100060
[    0.002446] rcu: Hierarchical SRCU implementation.
[    0.002734] smp: Bringing up secondary CPUs ...
[    0.003511] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
[    0.003521] CPU1: Spectre v2: using BPIALL workaround
[    0.003660] smp: Brought up 1 node, 2 CPUs
[    0.003673] SMP: Total of 2 processors activated (1333.33 BogoMIPS).
[    0.003680] CPU: All CPU(s) started in SVC mode.
[    0.004149] devtmpfs: initialized
[    0.007907] VFP support v0.3: implementor 41 architecture 3 part 30 variant 9 rev 4
[    0.008389] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.008417] futex hash table entries: 512 (order: 3, 32768 bytes, linear)
[    0.014526] pinctrl core: initialized pinctrl subsystem
[    0.015705] NET: Registered protocol family 16
[    0.017924] DMA: preallocated 256 KiB pool for atomic coherent allocations
[    0.019294] thermal_sys: Registered thermal governor 'step_wise'
[    0.072675] hw-breakpoint: found 5 (+1 reserved) breakpoint and 1 watchpoint registers.
[    0.072695] hw-breakpoint: maximum watchpoint size is 4 bytes.
[    0.072841] zynq-ocm f800c000.ocmc: ZYNQ OCM pool: 256 KiB @ 0x(ptrval)
[    0.073668] e0001000.serial: ttyPS0 at MMIO 0xe0001000 (irq = 33, base_baud = 6249999) is a xuartps
[    0.453870] printk: console [ttyPS0] enabled
[    0.490881] SCSI subsystem initialized
[    0.493609] usbcore: registered new interface driver usbfs
[    0.497849] usbcore: registered new interface driver hub
[    0.501971] usbcore: registered new device driver usb
[    0.506011] mc: Linux media interface: v0.10
[    0.509034] videodev: Linux video capture interface: v2.00
[    0.513422] pps_core: LinuxPPS API ver. 1 registered
[    0.517080] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.525020] PTP clock support registered
[    0.528048] jesd204: found 0 devices and 0 topologies
[    0.531878] FPGA manager framework
[    0.534054] Advanced Linux Sound Architecture Driver Initialized.
[    0.540323] clocksource: Switched to clocksource arm_global_timer
[    0.556219] NET: Registered protocol family 2
[    0.559951] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 6144 bytes, linear)
[    0.567041] TCP established hash table entries: 4096 (order: 2, 16384 bytes, linear)
[    0.573543] TCP bind hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    0.579439] TCP: Hash tables configured (established 4096 bind 4096)
[    0.584609] UDP hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.589849] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.595725] NET: Registered protocol family 1
[    0.599196] hw perfevents: no interrupt-affinity property for /pmu@f8891000, guessing.
[    0.606027] hw perfevents: enabled with armv7_cortex_a9 PMU driver, 7 counters available
[    0.614191] Initialise system trusted keyrings
[    0.617478] workingset: timestamp_bits=30 max_order=17 bucket_order=0
[    0.732568] Key type asymmetric registered
[    0.735357] Asymmetric key parser 'x509' registered
[    0.738936] io scheduler mq-deadline registered
[    0.742174] io scheduler kyber registered
[    0.745216] zynq-pinctrl 700.pinctrl: zynq pinctrl initialized
[    0.753785] dma-pl330 f8003000.dmac: Loaded driver for PL330 DMAC-241330
[    0.759189] dma-pl330 f8003000.dmac:         DBUFF-128x8bytes Num_Chans-8 Num_Peri-4 Num_Events-16
[    0.776410] brd: module loaded
[    0.786498] loop: module loaded
[    0.792093] spi-nor spi1.0: SPI-NOR-UniqueID 104473e26991000e16002b00a3a28b61c9
[    0.798099] spi-nor spi1.0: found n25q256ax1, expected n25q256a
[    0.802985] spi-nor spi1.0: trying to lock already unlocked area
[    0.807682] spi-nor spi1.0: n25q256ax1 (32768 Kbytes)
[    0.811583] 6 fixed-partitions partitions found on MTD device spi1.0
[    0.816626] Creating 6 MTD partitions on "spi1.0":
[    0.820116] 0x000000000000-0x0000000e0000 : "qspi-fsbl-uboot"
[    0.831153] 0x0000000e0000-0x000000100000 : "qspi-uboot-env"
[    0.841144] 0x000000100000-0x000000600000 : "qspi-linux"
[    0.851136] 0x000000600000-0x000000620000 : "qspi-device-tree"
[    0.861103] 0x000000620000-0x000001300000 : "qspi-rootfs"
[    0.871153] 0x000001300000-0x000002000000 : "qspi-bitstream"
[    0.881450] MACsec IEEE 802.1AE
[    0.883894] libphy: Fixed MDIO Bus: probed
[    0.887515] tun: Universal TUN/TAP device driver, 1.6
[    0.893132] libphy: MACB_mii_bus: probed
[    0.897123] macb e000b000.ethernet eth0: Cadence GEM rev 0x00020118 at 0xe000b000 irq 36 (00:02:b5:01:07:ad)
[    0.906446] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    0.911782] usbcore: registered new interface driver usb-storage
[    0.916607] usbcore: registered new interface driver usbserial_generic
[    0.921885] usbserial: USB Serial support registered for generic
[    0.926627] usbcore: registered new interface driver ftdi_sio
[    0.931115] usbserial: USB Serial support registered for FTDI USB Serial Device
[    0.990284] ULPI transceiver vendor/product ID 0x0424/0x0007
[    0.994636] Found SMSC USB3320 ULPI transceiver.
[    0.997950] ULPI integrity check: passed.
[    1.000687] ci_hdrc ci_hdrc.0: EHCI Host Controller
[    1.004277] ci_hdrc ci_hdrc.0: new USB bus registered, assigned bus number 1
[    1.040280] ci_hdrc ci_hdrc.0: USB 2.0 started, EHCI 1.00
[    1.045093] hub 1-0:1.0: USB hub found
[    1.047573] hub 1-0:1.0: 1 port detected
[    1.052503] i2c /dev entries driver
[    1.056279] at24 0-0050: supply vcc not found, using dummy regulator
[    1.062285] at24 0-0050: 4096 byte 24c32 EEPROM, writable, 1 bytes/write
[    1.068158] IR NEC protocol handler initialized
[    1.071451] IR RC5(x/sz) protocol handler initialized
[    1.075194] IR RC6 protocol handler initialized
[    1.078413] IR JVC protocol handler initialized
[    1.081642] IR Sony protocol handler initialized
[    1.084941] IR SANYO protocol handler initialized
[    1.088326] IR Sharp protocol handler initialized
[    1.091743] IR MCE Keyboard/mouse protocol handler initialized
[    1.096260] IR XMP protocol handler initialized
[    1.099843] usbcore: registered new interface driver uvcvideo
[    1.104317] USB Video Class driver (1.1.1)
[    1.107102] gspca_main: v2.14.0 registered
[    1.110959] cdns-wdt f8005000.watchdog: Xilinx Watchdog Timer with timeout 10s
[    1.117272] Xilinx Zynq CpuIdle Driver started
[    1.120445] failed to register cpuidle driver
[    1.123840] sdhci: Secure Digital Host Controller Interface driver
[    1.128706] sdhci: Copyright(c) Pierre Ossman
[    1.131776] sdhci-pltfm: SDHCI platform and OF driver helper
[    1.137557] ledtrig-cpu: registered to indicate activity on CPUs
[    1.142499] hid: raw HID events driver (C) Jiri Kosina
[    1.153535] usbcore: registered new interface driver usbhid
[    1.157803] usbhid: USB HID core driver
[    1.162915] mmc0: SDHCI controller on e0100000.mmc [e0100000.mmc] using ADMA
[    1.163096] ad7291: probe of 0-002f failed with error -5
[    1.183777] fpga_manager fpga0: Xilinx Zynq FPGA Manager registered
[    1.192630] xt_time: kernel timezone is -0000
[    1.196218] ipt_CLUSTERIP: ClusterIP Version 0.8 loaded successfully
[    1.201485] NET: Registered protocol family 17
[    1.204842] Registering SWP/SWPB emulation handler
[    1.208542] Loading compiled-in X.509 certificates
[    1.222881] input: gpio_keys as /devices/soc0/gpio_keys/input/input0
[    1.229322] clk: Not disabling unused clocks
[    1.232863] ALSA device list:
[    1.234516]   No soundcards found.
[    1.236687] mmc0: new high speed SDHC card at address b36b
[    1.241305] Waiting for root device /dev/mmcblk0p2...
[    1.241589] mmcblk0: mmc0:b36b SDABC 29.3 GiB
[    1.250045]  mmcblk0: p1 p2 p3
[    1.394025] random: fast init done
[    1.452430] EXT4-fs (mmcblk0p2): recovery complete
[    1.457058] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    1.463912] VFS: Mounted root (ext4 filesystem) on device 179:2.
[    1.476325] devtmpfs: mounted
[    1.479439] Freeing unused kernel memory: 1024K
[    1.483114] Run /sbin/init as init process
[    1.485894]   with arguments:
[    1.485900]     /sbin/init
[    1.485904]   with environment:
[    1.485909]     HOME=/
[    1.485913]     TERM=linux
[    2.043828] systemd[1]: System time before build time, advancing clock.
[    2.082051] systemd[1]: Failed to find module 'autofs4'
[    2.711321] NET: Registered protocol family 10
[    2.715483] Segment Routing with IPv6
[    2.745949] systemd[1]: systemd 247.3-7+rpi1 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified)
[    2.771853] systemd[1]: Detected architecture arm.
[    2.831102] systemd[1]: Set hostname to <analog>.
[    4.590947] systemd[1]: /lib/systemd/system/plymouth-start.service:16: Unit configured to use KillMode=none. This is unsafe, as it disables systemd's process lifecycle management for the service. Please update your service to use a safer KillMode=, such as 'mixed' or 'control-group'. Support for KillMode=none is deprecated and will eventually be removed.
[    4.954920] systemd[1]: Queued start job for default target Graphical Interface.
[    4.963251] random: systemd: uninitialized urandom read (16 bytes read)
[    4.968891] systemd[1]: system-getty.slice: unit configures an IP firewall, but the local system does not support BPF/cgroup firewalling.
[    4.979975] systemd[1]: (This warning is only shown for the first unit using IP firewalling.)
[    4.988252] systemd[1]: Created slice system-getty.slice.
[    5.020531] random: systemd: uninitialized urandom read (16 bytes read)
[    5.026668] systemd[1]: Created slice system-modprobe.slice.
[    5.060444] random: systemd: uninitialized urandom read (16 bytes read)
[    5.066547] systemd[1]: Created slice system-serial\x2dgetty.slice.
[    5.101231] systemd[1]: Created slice system-systemd\x2dfsck.slice.
[    5.141020] systemd[1]: Created slice User and Session Slice.
[    5.180906] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
[    5.220944] systemd[1]: Condition check resulted in Arbitrary Executable File Formats File System Automount Point being skipped.
[    5.232636] systemd[1]: Reached target Slices.
[    5.270649] systemd[1]: Reached target Swap.
[    5.311710] systemd[1]: Listening on Syslog Socket.
[    5.351119] systemd[1]: Listening on fsck to fsckd communication Socket.
[    5.400819] systemd[1]: Listening on initctl Compatibility Named Pipe.
[    5.475504] systemd[1]: Condition check resulted in Journal Audit Socket being skipped.
[    5.483245] systemd[1]: Listening on Journal Socket (/dev/log).
[    5.531483] systemd[1]: Listening on Journal Socket.
[    5.578938] systemd[1]: Listening on udev Control Socket.
[    5.621162] systemd[1]: Listening on udev Kernel Socket.
[    5.671181] systemd[1]: Condition check resulted in Huge Pages File System being skipped.
[    5.678654] systemd[1]: Condition check resulted in POSIX Message Queue File System being skipped.
[    5.689690] systemd[1]: Mounting RPC Pipe File System...
[    5.723756] systemd[1]: Mounting Kernel Debug File System...
[    5.750999] systemd[1]: Condition check resulted in Kernel Trace File System being skipped.
[    5.758452] systemd[1]: Condition check resulted in Kernel Module supporting RPCSEC_GSS being skipped.
[    5.771641] systemd[1]: Starting Restore / save the current clock...
[    5.815517] systemd[1]: Starting Set the console keyboard layout...
[    5.850787] systemd[1]: Condition check resulted in Create list of static device nodes for the current kernel being skipped.
[    5.865774] systemd[1]: Starting Load Kernel Module configfs...
[    5.903967] systemd[1]: Starting Load Kernel Module drm...
[    5.933936] systemd[1]: Starting Load Kernel Module fuse...
[    5.964105] systemd[1]: Condition check resulted in Set Up Additional Binary Formats being skipped.
[    5.972359] systemd[1]: Condition check resulted in File System Check on Root Device being skipped.
[    5.984162] systemd[1]: Starting Journal Service...
[    6.016067] systemd[1]: Starting Load Kernel Modules...
[    6.063763] systemd[1]: Starting Remount Root and Kernel File Systems...
[    6.103843] systemd[1]: Starting Coldplug All udev Devices...
[    6.140778] systemd[1]: run-rpc_pipefs.mount: Mount process exited, code=exited, status=32/n/a
[    6.170558] systemd[1]: run-rpc_pipefs.mount: Failed with result 'exit-code'.
[    6.177698] systemd[1]: Failed to mount RPC Pipe File System.
[    6.240532] systemd[1]: Dependency failed for RPC security service for NFS server.
[    6.280564] systemd[1]: rpc-svcgssd.service: Job rpc-svcgssd.service/start failed with result 'dependency'.
[    6.289136] systemd[1]: Dependency failed for RPC security service for NFS client and server.
[    6.340718] systemd[1]: rpc-gssd.service: Job rpc-gssd.service/start failed with result 'dependency'.
[    6.366015] systemd[1]: Started Journal Service.
[    6.442066] random: crng init done
[    6.444168] random: 7 urandom warning(s) missed due to ratelimiting
[    6.842908] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[    7.075499] systemd-journald[1092]: Received client request to flush runtime journal.
[    7.103487] systemd-journald[1092]: File /var/log/journal/9a314adf4f7b4c659ada5035385c9b39/system.journal corrupted or uncleanly shut down, renaming and replacing.
[    9.321957] Registered mathworks_ip class
[    9.409007] mwipcore 43c00000.mwipcore: IRQ index 0 not found
[    9.409032] mwipcore 43c00000.mwipcore: Dev memory resource found at 106b933f 0000FFFF.
[    9.409066] mwipcore 43c00000.mwipcore: 'mwipcore' device not found, creating
[    9.409079] mwipcore 43c00000.mwipcore: Char dev region registered: major num:240
[    9.409087] mwipcore 43c00000.mwipcore: 'mwipcore' device created
[   11.873811] macb e000b000.ethernet eth0: PHY [e000b000.ethernet-ffffffff:00] driver [Marvell 88E1510] (irq=POLL)
[   11.873845] macb e000b000.ethernet eth0: configuring for phy/rgmii-id link mode
[   12.149164] 8021q: 802.1Q VLAN Support v1.8
[   12.740347] Adding 102396k swap on /var/swap.  Priority:-2 extents:1 across:102396k SS
[   12.806878] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[   12.948391] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[   12.965396] cfg80211: loaded regulatory.db is malformed or signature is missing/invalid
[   15.058726] systemd-journald[1092]: File /var/log/journal/9a314adf4f7b4c659ada5035385c9b39/user-1000.journal corrupted or uncleanly shut down, renaming and replacing.
[   30.222757] PM: suspend entry (deep)

2, I download the image file from open-sdr/opemwifi yesterday, I think it's the latest image file.

3, No, but  I use the new SD card, and the file for other board is OK.(e310V2, zedboard+fmcomms3).

**Comment by JiaoXianjun** [comment]
What is your hardware revision: https://wiki.analog.com/resources/eval/user-guides/adrv9361-z7035/revision-history
What is your carrier board:

[FMC Carrier (PZSDRCC-FMC)](https://wiki.analog.com/resources/eval/user-guides/pzsdr/carriers/fmc)
[Breakout Carrier (PZSDRCC-BRK)](https://wiki.analog.com/resources/eval/user-guides/pzsdr/carriers/brk)
[PCIe Carrier (PZSDRCC-PCIE)](https://wiki.analog.com/resources/eval/user-guides/pzsdr/carriers/pcie)
[PackRF Carrier (PZSDRCC-PackRF)](https://wiki.analog.com/resources/eval/user-guides/pzsdr/carriers/packrf)

**Comment by frigo125** [comment]
My hardware is Revision E, 
My carrier board is  Breakout Carrier (PZSDRCC-BRK).

Thank you .

**Comment by frigo125** [comment]
Hello DR.JIAO,
Can you help me to review this question? 
The last question is my device (adrv9361-z7035) is freezing after booting.
However, I did not do anything, just reboot the device.  but this time, it's work. I dont know what's happened. 
Could it be a hardware problem?

**Comment by snailxgh** [comment]
I have the same problem,
My hardware is Revision FAILED
My carrier board is FMC Carrier (PZSDRCC-FMC)

Did you solve it ???

**Comment by snailxgh** [comment]
> 1. Could save the dmesg output right after its booting? (before freezing)
> 
>     2. Could you make sure use our latest img? (old img's devicetree could cause this issue)
> 
>     3. Could you try different SD card flashing tool under different OS?

I replaced the device tre and system_top.xsa file, and it doesn't shutdown

**Comment by JiaoXianjun** [comment]
We don’t have this issue on our hardwares. So it is difficult for us to know. 

Sometimes, change the SD card ( size, brand, type) and the flashing tool (windows, Linux) help.
