### ISSUE TITLE
OpenWifi on the ADRV9001/Navassa chip

### ISSUE THREAD

**Issue by Jcrash29** [open-sdr/openwifi#324]
I am very interested in your work, but would like to see it running on a ADRV 9001 rather than the  9361. Do you know if anyone has done this before? How much effort would you say it would be to port the code to a 9001/Navassa platform.

I started working on converting the FPGA (ZED Board) to use a 9001 FPGA core instead, but started to run into problems with some of the driver code. Do you have any advice for a Port to the ZED board + ADRV 9001? Can you think of any reason this wouldn't work?

**Comment by JiaoXianjun** [comment]
sorry that we mainly focus on fpga baseband.
so far, the ad9361 is good for us (unless there is strong motivation/investment from inside/outside).
