### ISSUE TITLE
Can OpenWiFi work properly with a 2 Mbps bandwidth?

### ISSUE THREAD

**Issue by huangfu001206** [open-sdr/openwifi#325]
Hello, Dr. Jiao! I am a student who is currently studying the openwifi project. I wanted to try if it can work properly with a 2 Mbps bandwidth. So, I made some modifications to the driver script, wgd.sh, and changed the following configurations:

echo 2241370 > in_voltage_rf_bandwidth
echo 2272947 > out_voltage_rf_bandwidth
echo 4000000 > in_voltage_sampling_frequency
echo 4000000 > out_voltage_sampling_frequency

I also used the tools provided by ADI to generate the filter file. However, I found that when I try to load the modules like 'insmod tx/rx_intf.ko' and 'xpu', the operating system crashes immediately. Through step-by-step debugging, I discovered that the crash occurs when writing to the register with 'tx_intf_api->TX_INTF_REG_MULTI_RST_write(0)'. So, I wanted to ask you, Dr. Jiao, what do you think could be causing this problem? Thank you.

**Comment by JiaoXianjun** [comment]
https://github.com/open-sdr/openwifi/issues/155
