### ISSUE TITLE
adrv9361z7035 not found /lib/modules/adi-linux

### ISSUE THREAD

**Issue by snailxgh** [open-sdr/openwifi#327]
root@analog:~/openwifi# ./post_config.sh 
++ uname -m
+ MACHINE_TYPE=armv7l
++ uname -r
+ '[' -d /lib/modules/5.10.0-98248-g1bbe32fa5182-dirty ']'
+ '[' armv7l == aarch64 ']'
++ uname -r
+ ln -s /lib/modules/adi-linux /lib/modules/5.10.0-98248-g1bbe32fa5182-dirty
+ depmod
depmod: ERROR: could not open directory /lib/modules/5.10.0-98248-g1bbe32fa5182-dirty: No such file or directory
depmod: FATAL: could not search modules: No such file or directory

startup info :

systemd[1]: run-rpc_pipefs.mount: Mount process exited, code=exited, status=32/n/a
systemd[1]: run-rpc_pipefs.mount: Failed with result 'exit-code'.
systemd[1]: Failed to mount RPC Pipe File System.
[FAILED] Failed to mount RPC Pipe File System.
See 'systemctl status run-rpc_pipefs.mount' for details.
systemd[1]: Dependency failed for RPC security service for NFS server.
[DEPEND] Dependency failed for RPC …curity service for NFS server.
systemd[1]: rpc-svcgssd.service: Job rpc-svcgssd.service/start failed with result 'dependency'.
systemd[1]: Dependency failed for RPC security service for NFS client and server.
[DEPEND] Dependency failed for RPC …ice for NFS client and server.
systemd[1]: rpc-gssd.service: Job rpc-gssd.service/start failed with result 'dependency'.
systemd[1]: Started Journal Service.
[  OK  ] Started Journal Service.
random: crng init done
random: 7 urandom warning(s) missed due to ratelimiting
[  OK  ] Mounted Kernel Debug File System.
[  OK  ] Finished Restore / save the current clock.
[  OK  ] Finished Load Kernel Module configfs.
[  OK  ] Finished Load Kernel Module drm.
[  OK  ] Finished Load Kernel Module fuse.
[FAILED] Failed to start Load Kernel Modules.
See 'systemctl status systemd-modules-load.service' for details.
[  OK  ] Reached target NFS client services.
...
[  OK  ] Started IIO Daemon.
         Starting Light Display Manager...
         Starting Hold until boot process finishes up...
[  OK  ] Started LSB: Webfs simple HTTP server.
[  OK  ] Started OpenBSD Secure Shell server.
[FAILED] Failed to start VNC Server for X11.
[FAILED] Failed to start LSB: DHCP server.

**Comment by JiaoXianjun** [comment]
Try this:

https://github.com/open-sdr/openwifi/issues/334#issuecomment-1676886785

**Comment by AlexeyIgnatev** [comment]
Hello, have you found a solution for this problem? Provided solution does not work because there is no ssh access to the board
