### ISSUE TITLE
How to Change BW and Sample Rate Values

### ISSUE THREAD

**Issue by Baraday3** [open-sdr/openwifi#335]
0. Could you send email to xianjun.jiao@ugent.be to introduce your self?
Sent earlier.

1. Our image is used directly or you build your own image?
Latest image is used

2. What is your own modification? 
Nothing

3. Versions: OS, Vivado, openwifi/openwifi-hw repo branch and commit revision
Ubuntu 18.04, Vivado 2021.1, openwifi master

4. Board/hardware type
Zedboard+FMCOMMS4

I would like to set RX/TX BW and sample rates to other values. In the read me it is mentioned that 2 MHz channel can be used. How can I do it? I checked this issue https://github.com/open-sdr/openwifi/issues/155 but I do not want to increase or modify to any other random BW and sample rate. I just want to use mentioned 2 MHz channel in ad-hoc mode. If it is possible, I would also use BW and sample rate asymmetric for TX and RX. For example same as 20 MHz for TX and 2 MHz for RX. 

![image](https://github.com/open-sdr/openwifi/assets/9075262/e392dd44-9c41-48b2-8ce7-6d44c01d5ddd)

Thank you for your help

**Comment by JiaoXianjun** [comment]
Issue 155 is the general description of how to do your work. You need to understand the design, and take care of all details mentioned in issue 155.
