### ISSUE TITLE
The latest code lacks necessary files？

### ISSUE THREAD

**Issue by changcongliu** [open-sdr/openwifi#35]
When compiling sdr.ko, it was found that the necessary header file #include "git_rev.h" was missing

**Comment by JiaoXianjun** [comment]
If you build the driver by: https://github.com/open-sdr/openwifi/blob/master/driver/make_all.sh
git_rev.h should be generated automatically.
Please check the script output (if you run it) to confirm the git_rev.h is generated or not.

**Comment by JiaoXianjun** [comment]
Is your issue resolved?

**Comment by changcongliu** [comment]
It's solved, thank you very much, Teacher Jiao!
