### ISSUE TITLE
 How can you define the SW/driver clock is 10 MHz

### ISSUE THREAD

**Issue by DatPhungThe** [open-sdr/openwifi#36]
Hi all,
In `board_def.v`, I see a definition: 

`define ASSUMED_COUNTER_CLK_MHZ 10  // 10MHz is assumed in SW/driver for sub us resolutuion FPGA counters`

Why is 10 MHz ? Could you please give me the explanation of this value ?

Thank you very much !
Best Regards,
 Dat Phung The

**Comment by JiaoXianjun** [comment]
that is just an assumption. you need to read the code.
