### ISSUE TITLE
open WiFi丢包率相关问题

### ISSUE THREAD

**Issue by joker1-m** [open-sdr/openwifi#380]
焦博士您好！请问为什么将两块板子用同轴电缆相连，也会丢包，并且将最大重传次数定为1时，两块板子用同轴电缆相连丢包率达到了7%，丢包的问题大概会出现在哪些地方？

**Comment by JiaoXianjun** [comment]
PHY MAC Linux, all possible. You can dig further by the rich ways we offered:
https://github.com/open-sdr/openwifi/blob/master/doc/README.md#Debug-methods
https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/perf_counter.md
https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/driver_stat.md
