### ISSUE TITLE
Update the uImage 

### ISSUE THREAD

**Issue by Maxelectronics** [open-sdr/openwifi#381]
I am reaching out to address an issue I've encountered with the uImage in the new kernel version, which seems to be having trouble recognizing modules from the previous kernel version.

Upon further investigation, it appears that the uImage is not seamlessly recognizing the modules associated with the older kernel. I was wondering if there are any specific steps or configurations that need to be followed on Openwifi to address this compatibility issue.

I would greatly appreciate your guidance on whether there are any particular procedures or adjustments that can be made to ensure a smooth transition and recognition of modules in the new kernel version. Your expertise and assistance in resolving this matter would be immensely valuable.

Thank you for your time and support. I look forward to hearing from you soon.

**Comment by JiaoXianjun** [comment]
https://github.com/open-sdr/openwifi/blob/master/doc/img_build_instruction/kuiper.md
