### ISSUE TITLE
CSI Phase keeps changing Despite relatively stable environment

### ISSUE THREAD

**Issue by ThETyMaNp** [open-sdr/openwifi#396]
Hi, I tried to use this demo and was able to get a better looking constellation(https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/radar-self-csi.md), but the problem is thar the CSI phase keeps changing abruptly despite relatively stable environment.

[What is your own modification?]I modified the code in python so that it displays the csi and its phase, as well as the frequency deviation.

I measured the CSI while keeping the transceiver antenna stationary and the surroundings relatively stable (I even went to a darkroom to measure it), but found that even though the surroundings were relatively stable, the phase of the CSI still changed abruptly, and the value of this abrupt change is relatively regular.I initially thought it was due to a sudden phase change in the CSI due to the frequency offset, however, during later tests, the CSI still had a sudden phase change with a frequency offset of 0 (the amplitude information was normal)
<img width="459" alt="Snipaste_2024-03-18_20-44-19" src="https://github.com/open-sdr/openwifi/assets/138379342/6b73010d-31e6-4dd7-addf-73107b4e21d6">
In this picture,  I have printed only one subcarrier information, which are phase(angle), frequency offset, csi.Inside each bracket is a time frame (there seem to be several timestamps inside each frame), printed in chronological order
<img width="925" alt="Snipaste_2024-03-18_20-52-19" src="https://github.com/open-sdr/openwifi/assets/138379342/d75c7599-e3cd-4854-a26c-07a113438ce9">
As a sophomore in college, I am limited in my ability and shallow in my knowledge.Therefore ,this question has been troubling me for a long time, so I'm taking the liberty of asking for your advice, hoping that my question wouldn't bother you and you'll come to help me out!
Sincerely,
Guang Liu.

**Comment by JiaoXianjun** [comment]
to have stable wifi radar signal/phase, you need to use the iq capture functionality:
https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/packet-iq-self-loopback-test.md#iq-self-loopback-quick-start 

Please use the trigger condition 3:
3 	the tx_intf_iq0 becomes non zero (the 1st I/Q out)
https://github.com/open-sdr/openwifi-hw/blob/900aa8f4c330d047660e10ac871fff922f44aa98/ip/side_ch/src/side_ch_control.v#L460C35-L460C55

You should start do this from a setup with tx antenna rx antenna very close, and a quite low rx gain (check how to set rx gain in manual gain mode not AGC gain mode : https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/frequent_trick.md  )

You can monitor the iq plot via our python script, and adjust the rx gain manually to have IQ amplitude not too big (clipping) not too small (too low SNR).

After you have stable iq loop back over the air (closely co-located tx and rx antenna), you should see very stable stf and ltf in the captured IQ real-time plot.

You can calculate the IQ sample phase difference between "all captures" and "the 1st captures". it is very stable. 

You can also easily write a python script to calculate real-time CSI based on captured ltf IQ. (fft, divided by the tx ltf frequency domain signal, etc.)

**Comment by ThETyMaNp** [comment]
Thx very much for your help！I'll try it as soon as I can

**Comment by ThETyMaNp** [comment]
Thank you again for your sincere help, I followed your instructions, first I put the transceiver antennas very close to each other (I used two horn antennas about 30cm apart), then I adjusted the gain of the RX to 30 (I got a gain of about 41 at the actual reception), and adjusted the trigger mode to 3. Here are the commands I used to run it:

>In one ssh:
ssh root@192.168.10.122
cd openwifi
./wgd.sh
./monitor_ch.sh sdr0 44		
./sdrctl dev sdr0 set reg xpu 8 1000	
insmod side_ch.ko iq_len_init=4095	
./side_ch_ctl wh11d100		
./side_ch_ctl wh8d3		
./sdrctl dev sdr0 set reg xpu 1 1	
./side_ch_ctl wh5h0	
./set_rx_gain_manual.sh 30		//30dB
./side_ch_ctl g0	

> In another ssh:
cd openwifi/inject_80211/
(make)
./inject_80211 -m n -r 5 -n 1 sdr0

> on computer:
python iq_capture.py 4095

I then ran it several times in a second ssh session:
 /inject_80211 -m n -r 5 -n 1 sdr0

Here are the IQ figures I got in order:
<img width="962" alt="Snipaste_2024-03-20_09-34-36" src="https://github.com/open-sdr/openwifi/assets/138379342/f59ab69c-729f-4c56-b56d-6bc49033fc25">
<img width="482" alt="Snipaste_2024-03-20_09-34-59" src="https://github.com/open-sdr/openwifi/assets/138379342/ef00f9ab-255c-4b14-ad02-94a648f05309">
<img width="482" alt="Snipaste_2024-03-20_09-35-07" src="https://github.com/open-sdr/openwifi/assets/138379342/06facb28-d03e-44a4-a2b7-a87a0178766a">
<img width="482" alt="Snipaste_2024-03-20_09-35-42" src="https://github.com/open-sdr/openwifi/assets/138379342/de0f32f4-9ea5-4d44-b3c9-d7082cbad0db">
<img width="482" alt="Snipaste_2024-03-20_09-35-48" src="https://github.com/open-sdr/openwifi/assets/138379342/69a80e87-593f-49ad-b529-89673f3733fe">
<img width="482" alt="Snipaste_2024-03-20_09-35-56" src="https://github.com/open-sdr/openwifi/assets/138379342/6ffc1153-9b98-41e1-9322-4c68de842533">
<img width="482" alt="Snipaste_2024-03-20_09-36-02" src="https://github.com/open-sdr/openwifi/assets/138379342/a62e17aa-5def-4ea6-890a-c1449269ef1e">
<img width="482" alt="Snipaste_2024-03-20_09-36-07" src="https://github.com/open-sdr/openwifi/assets/138379342/00248220-b169-4d89-b0fb-1590c95ad062">

Question:
Since I don't really understand what stf and ltf sequences are supposed to look like or how to tell if they are stable or not, I'll take the liberty of bothering you and ask if this is considered to be obtaining a stable ltf sequence?
If so,can I start the next step of calculating the csi?

I sincerely hope that you can give me some advice.Thank you again!!!：）
Sincerely,
Guangteng Liu.

**Comment by petrichorZSY** [comment]
Hello, I would like to ask you how you process CSI, frequency offset and other information, and how you print it out. What does this information have to do with the side_info.txt file? I would really appreciate it if you could reply to me

**Comment by ThETyMaNp** [comment]
Hello,

You can obtain the measurement information by running side_info_display.py, which will save it to side_info.txt for further MATLAB data processing. CSI and frequency offset data can also be acquired by creating Python scripts based on side_info_display.py.

**Comment by JiaoXianjun** [comment]
You might also need to disable our Tx LO automatic control. Because each time LO ON/OFF, the phase might be different. 

Check the xpu register 13. Set it to 1 will disable it.

**Comment by ThETyMaNp** [comment]
Thank you very much for your prompt response. I have made an attempt to incorporate control for register 13 at the indicated location. The code is as follows:
`ssh root@192.168.10.122
cd openwifi
./wgd.sh
./monitor_ch.sh sdr0 44		
./sdrctl dev sdr0 set reg xpu 8 1000	
insmod side_ch.ko iq_len_init=4095	
./side_ch_ctl wh11d100		
./side_ch_ctl wh8d3		
(./side_ch_ctl wh13d1)
./sdrctl dev sdr0 set reg xpu 1 1	
./side_ch_ctl wh5h0	
./set_rx_gain_manual.sh 30	
./side_ch_ctl g0	`
But the results I obtained are still as follows：
<img width="420" alt="Snipaste_2024-05-03_19-05-07" src="https://github.com/open-sdr/openwifi/assets/138379342/eb305b8d-34a7-4020-9935-22ae4276e466">

**Comment by ThETyMaNp** [comment]
Made it!!!
Thanks for your generous help!!!My gratitude is beyond words!
：）
