### ISSUE TITLE
Cannot find the E310v2 kernel in BOOT/openwifi/ after burning the SD card

### ISSUE THREAD

**Issue by AnVuNam** [open-sdr/openwifi#410]
0. Could you send email to xianjun.jiao@ugent.be to introduce your self?
Yes, I sent it.

1. Our image is used directly or you build your own image?
I use your image directly (openwifi-1.4.0-notter.img.xz).

2. What is your own modification?
None.

3. Versions: OS, Vivado, openwifi/openwifi-hw repo branch and commit revision
Focal Fossa, Vivado 2021.1, open wifi 1.4.0 in master branch.

4. Board/hardware type
Antsdr E310v2

5. WiFi channel number
None.

6. Steps to reproduce the issue, and the related error message, screenshot, etc
I downloaded the image in Quick Start and then burned it to a 32GB SD card. After burning, only a BOOT folder appears. However, in the BOOT/openwifi/ folder, there is no e310v2 folder.

7. Describe your debug efforts by Linux native tools, such as tcpdump and "cat /proc/interrupts"
None.

8. Describe your debug efforts by: https://github.com/open-sdr/openwifi/blob/master/doc/README.md#Debug-methods
None.

9. Any other thing we need to know for helping you better? 
None.

**Comment by AnVuNam** [comment]
Thank you, I will try it.

Vào Th 6, 31 thg 5, 2024 vào lúc 15:04 Jiao Xianjun <
***@***.***> đã viết:

**Comment by AnVuNam** [comment]
> I think that is because antsdr e310v2 was added after that release. That's why it is not in the SD card. You need to build/update the SD card by yourself:
> 
> https://github.com/open-sdr/openwifi?tab=readme-ov-file#Build-openwifi-Linux-img-from-scratch

Hi, I have a problem while building an openwifi image from scratch. When building the FPGA image as instructed at [openwifi-hw repo](https://github.com/open-sdr/openwifi-hw) at the step `source ./openwifi.tcl`, I get the error "Incompatible IP data detected":

![image](https://github.com/open-sdr/openwifi/assets/135087211/1fb76596-a9aa-45ce-8a8d-5d994c5eebb2)

I tried upgrading this IP but got the following errors:

![image](https://github.com/open-sdr/openwifi/assets/135087211/c250aa30-16ca-4e31-afa2-68e5688aa279)

Do you have any advice to solve it?

Sorry if my question seems dumb because I have never used Vivado before.

**Comment by JiaoXianjun** [comment]
Please share what you have done (command and outputs) starting from git clone, then I can take a look.

**Comment by AnVuNam** [comment]
Oh sorry, I solved the problem but forgot to update the result.
Perhaps the problem is in the Vivado Design Suit installation process. After a clean install of Vivado and openwifi-hw repository, the problem was resolved. Thank you for your attention.
