### ISSUE TITLE
Error reporting about CSI radar

### ISSUE THREAD

**Issue by csy990406** [open-sdr/openwifi#412]
0. Could you send email to [xianjun.jiao@ugent.be](mailto:xianjun.jiao@ugent.be) to introduce your self?
yes

1. Our image is used directly or you build your own image?
use yours directly

2. What is your own modification?
none

3. Versions: OS, Vivado, openwifi/openwifi-hw repo branch and commit revision
Ubuntu 22.04, Vivado 2021.1 ,openwifi-1.4.0-notter.img.

4. Board/hardware type
MicroPhase Antsdr

5. WiFi channel number
none

6. Steps to reproduce the issue, and the related error message, screenshot, etc
none

7. Describe your debug efforts by Linux native tools, such as tcpdump and "cat /proc/interrupts"
none

8. Describe your debug efforts by: https://github.com/open-sdr/openwifi/blob/master/doc/README.md#Debug-methods
none

9. Any other thing we need to know for helping you better?
I find the following issue while trying to implement CSI radar (https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/radar-self-csi.md). According to the instructions, I need to execute the following command: "./drv_and_fpga_package_gen.sh $OPENWIFI_HW_IMG_DIR $XILINX_DIR $BOARD_NAME". However, an error occurs at line 42 of the openwifi/user_space/drv_and_fpga_package_gen.sh with the following command: unzip $OPENWIFI_HW_IMG_DIR/boards/$BOARD_NAME/sdk/system_top.xsa -d ./hdf_and_bit. I believe the issue is that the openwifi-hw/boards/sdk folder and the system_top.xsa file cannot be found. Where can I go to get /sdk/system_top.xsa?Thanks for your help.

**Comment by JiaoXianjun** [comment]
Please re-format the issue according to our issue template.

**Comment by csy990406** [comment]
> Can you share what have you done step by step (command and the outputs) from git clone to get that error?
![Uploading 截图 2024-06-12 18-51-17.png…]()

**Comment by csy990406** [comment]
> Can you share what have you done step by step (command and the outputs) from git clone to get that error?
csy@PC:~$ export XILINX_DIR=/opt/Xilinx
csy@PC:~$ export OPENWIFI_HW_IMG_DIR=/home/csy/openwifi-hw
csy@PC:~$ export BOARD_NAME=antsdr
csy@PC:~$ cd openwifi/user_space
csy@PC:~/openwifi/user_space$ ./drv_and_fpga_package_gen.sh $OPENWIFI_HW_IMG_DIR $XILINX_DIR $BOARD_NAME
$XILINX_DIR is found!
$BOARD_NAME is found!
$OPENWIFI_HW_IMG_DIR is found!
unzip:  cannot find or open /home/csy/openwifi-hw/boards/antsdr/sdk/system_top.xsa, /home/csy/openwifi-hw/boards/antsdr/sdk/system_top.xsa.zip or /home/csy/openwifi-hw/boards/antsdr/sdk/system_top.xsa.ZIP.
$BIT_FILENAME does NOT exist. Please check!

**Comment by JiaoXianjun** [comment]
which app note are you following? I remember that we describe the meaning of OPENWIFI_HW_IMG_DIR in some app note. could you look for it.

**Comment by csy990406** [comment]
> which app note are you following? I remember that we describe the meaning of OPENWIFI_HW_IMG_DIR in some app note. could you look for it.

Thank you for your response. After re-downloading the openwifi-hw-img, the issue has been resolved.
