### ISSUE TITLE
MCS problem

### ISSUE THREAD

**Issue by jyskr** [open-sdr/openwifi#416]
0. Could you send email to xianjun.jiao@ugent.be to introduce your self?
Yes
1. Our image is used directly or you build your own image?
yours(openwifi-1.4.0-notter.img)
2. What is your own modification?
no modification
3. Versions: OS, Vivado, openwifi/openwifi-hw repo branch and commit revision
Ubantu 18.04 ,,Just use openwifi-1.4.0-notter.img for Quick start.
4. Board/hardware type
antsdr
5. WiFi channel number
Default 5g(11)
6. Steps to reproduce the issue, and the related error message, screenshot, etc
None.
7. Describe your debug efforts by Linux native tools, such as tcpdump and "cat /proc/interrupts"
None.
8. Describe your debug efforts by: https://github.com/open-sdr/openwifi/blob/master/doc/README.md#Debug-methods
None.
9. Any other thing we need to know for helping you better? 
In high-throughput and non-high-throughput modes, you can control the Modulation and Coding Scheme (MCS) using ./sdrctl dev sdr0 0/1 x. In the sdrctl documentation, it is mentioned that when x is set to 0, the MCS is automatically controlled by Linux. I would like to know :
If this automatic switching of the MCS is based on channel characteristics?
Where exactly is the code that handles this?

**Comment by JiaoXianjun** [comment]
Please re-format the issue with our template. Thanks.

**Comment by jyskr** [comment]
> Please re-format the issue with our template. Thanks.

Dear Dr.Jiao, I have re_formatted it and encountered two issues that I need help with.

**Comment by HavingaThijs** [comment]
> If this automatic switching of the MCS is based on channel characteristics?

Linux uses the Minstel algorithm which looks at several metrics, including throughput estimation, see e.g.: https://wireless.wiki.kernel.org/en/developers/documentation/mac80211/ratecontrol/minstrel 

> Where exactly is the code that handles this?

For legacy packets, it would be [here](https://github.com/analogdevicesinc/linux/blob/b6e379910a11af77e6500ed8b0895006e471a279/net/mac80211/rc80211_minstrel.c) and for HT packets [here](https://github.com/analogdevicesinc/linux/blob/b6e379910a11af77e6500ed8b0895006e471a279/net/mac80211/rc80211_minstrel_ht.c).

**Comment by jyskr** [comment]
> > If this automatic switching of the MCS is based on channel characteristics?
> 
> Linux uses the Minstel algorithm which looks at several metrics, including throughput estimation, see e.g.: https://wireless.wiki.kernel.org/en/developers/documentation/mac80211/ratecontrol/minstrel
> 
> > Where exactly is the code that handles this?
> 
> For legacy packets, it would be [here](https://github.com/analogdevicesinc/linux/blob/b6e379910a11af77e6500ed8b0895006e471a279/net/mac80211/rc80211_minstrel.c) and for HT packets [here](https://github.com/analogdevicesinc/linux/blob/b6e379910a11af77e6500ed8b0895006e471a279/net/mac80211/rc80211_minstrel_ht.c).

Thank you very much for your response! It will help me a lot.
