### ISSUE TITLE
failed to Build openwifi Linux img from scratch

### ISSUE THREAD

**Issue by wolkenmeer911** [open-sdr/openwifi#49]
After compiling adi-linux and openwifi with zc706 project, I follow the step in Build openwifi Linux img from scratch. However, I can't run Linux successfully when burning it in SD card

**Comment by JiaoXianjun** [comment]
Hello,

Yes we can help. But firstly would you please send me (xianjun.jiao@ugent.be) information about you? where are you from? Student? (MS? PhD?), or employee of which company? Thanks!

**Comment by JiaoXianjun** [comment]
Can you tell us:

1 the git/revision of openwifi/openwifi-hw you are using. 

2 the error message.

**Comment by wolkenmeer911** [comment]
Hi，


Thanks for your replying,
I'm sorry that I don't know what the first question means. I saw openwifi-hw @ b3bd6e2 in the github if you mean it?
And the error message is that hostapd:command not found; webfsd:command not foune.







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiao Xianjun"<notifications@github.com&gt;; 
发送时间: 2020年12月14日(星期一) 下午2:18
收件人: "open-sdr/openwifi"<openwifi@noreply.github.com&gt;; 
抄送: "宋育升"<www.490757364@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [open-sdr/openwifi] failed to Build openwifi Linux img from scratch (#49)





 
Can you tell us:
 
1 the git/revision of openwifi/openwifi-hw you are using.
 
2 the error message.

**Comment by JiaoXianjun** [comment]
what is the output of:

cd ~/openwifi && ./post_config.sh

**Comment by wolkenmeer911** [comment]
There's no such file in openwifi, but there's a post_config.sh in user_space, do you mean this file?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiao Xianjun"<notifications@github.com&gt;; 
发送时间: 2020年12月14日(星期一) 下午2:55
收件人: "open-sdr/openwifi"<openwifi@noreply.github.com&gt;; 
抄送: "宋育升"<www.490757364@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [open-sdr/openwifi] failed to Build openwifi Linux img from scratch (#49)





 
what is the output of:
 
cd ~/openwifi &amp;&amp; ./post_config.sh

**Comment by JiaoXianjun** [comment]
You need to run that in board. Can you check the openwifi directory on board? You need to check and follow this section carefully:

https://github.com/open-sdr/openwifi#build-openwifi-linux-img-from-scratch

**Comment by wolkenmeer911** [comment]
I successfully ran the post_config.sh. When running&nbsp;fosdem.sh it occurs Interface sdr0 wasn't started.








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiao Xianjun"<notifications@github.com&gt;; 
发送时间: 2020年12月14日(星期一) 下午2:55
收件人: "open-sdr/openwifi"<openwifi@noreply.github.com&gt;; 
抄送: "宋育升"<www.490757364@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [open-sdr/openwifi] failed to Build openwifi Linux img from scratch (#49)





 
what is the output of:
 
cd ~/openwifi &amp;&amp; ./post_config.sh

**Comment by JiaoXianjun** [comment]
Can you share the full log of fosdem.sh?

**Comment by wolkenmeer911** [comment]
Sorry for replying you so late, I save the log as a txt file.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-sdr/openwifi"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月14日(星期一) 晚上9:44
收件人:&nbsp;"open-sdr/openwifi"<openwifi@noreply.github.com&gt;;
抄送:&nbsp;"宋育升"<www.490757364@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [open-sdr/openwifi] failed to Build openwifi Linux img from scratch (#49)





 
Can you share the full log of fosdem.sh?

**Comment by wolkenmeer911** [comment]
Sorry to bother you, I've solved the problem. I think the cause of it is that I didn't downald the complete project code due to the poor net. Apologize！
