### ISSUE TITLE
Using rf_init.sh script to configure the txpower gain does not take effect

### ISSUE THREAD

**Issue by L123ee** [open-sdr/openwifi#57]
Use the RF cable to directly connect tx and rx, but the direct connection causes too much power to communicate, so I need to modify the transmit power, but the gain can not be controlled through the rf_init.sh script to modify the power. How do I control the txpower?

**Comment by JiaoXianjun** [comment]
It is very risky connecting tx to rx. It might damage your rx. 
You need a attenuator in between. Or lower the tx power.

The rf_init.sh only set the initial attenuation. The real-time attenuation is controlled in driver sdr.c. Please search set_tx_att in sdr.c. You will see how we do tx power control by Analog devices API.
