### ISSUE TITLE
use openwifi_tx() to send a custom packet

### ISSUE THREAD

**Issue by 18845725896peng** [open-sdr/openwifi#66]
hello,
    excuse me ,recently I read the openwifi document ,sdr.c and learn about linux mac80211 subsystem. I learn the packet transmission between mac80211 and sdr driver,but I do not know how to use openwifi_tx() to send a custom packet(I  konw APIS such as ieee80211_subif_start_xmit,drv_tx()... but I have no idea about where to encapsulate data and use mac80211 to send a packet)? 
   Our company wants to use openwifi in TSN.

 thanks

**Comment by JiaoXianjun** [comment]
Hello,

Thanks for reaching us. We could take a look. Before that, would you please let us know whom we are helping? Could you send your information (name, organization/university/company, etc) from your organization email to my email xianjun.jiao@ugent.be?

Thanks!

**Comment by 18845725896peng** [comment]
hello,
We come from Chinese institute(771).The company's email can only be used through the intranet,sorry

thanks

**Comment by JiaoXianjun** [comment]
Hello,

"but I do not know how to use openwifi_tx() to send a custom packet" -- We have show you the source code of openwifi_tx(). By reading the source code of openwifi_tx(), you will know everything you need.

You need to come up with specific/concrete question, not like just "I don't know how to use the source code".

**Comment by 18845725896peng** [comment]
thanks for your reply
