### ISSUE TITLE
openwifi's boot processing

### ISSUE THREAD

**Issue by Shangjie-Yang** [open-sdr/openwifi#68]
Hi,

I am walking through the code in ./net/mac80211, I want to know:
1)Whether the boot process, is: after board is powered up, we run openwifi AP and the on board webserver,the system starts to initialize,the High Mac operations goes on in this process,and then after the sta0 access, the driver start to write register to support low mac?
2)How is the process of scan-auth-asso(high mac) started, I guess automatically after the system initialized?or there has a trigger? 
3)how can I change the beacon interval?

Thank you very much!

**Comment by weiliu1011** [comment]
HI Shangjie,

1) I think the order is rather like this, after booting up, in the fosdem.sh script, we first insert mac80211 kernel module (high MAC), then load our driver. The driver talks to the openwifi hardware (PHY and low MAC) from that moment on, no matter if there is a client connected or not. 
2) the authentication, scan operation is controlled by user space program, such as wpa_supplicant. So without running such kind of user program you won't start authentication etc activity. 
3) beacon interval can be specified in configuration file of hostapd application, you can take a look at [this link](http://w1.fi/cgit/hostap/plain/hostapd/hostapd.conf) , search for the "beacon_int" parameter
Best,
Wei

**Comment by Shangjie-Yang** [comment]
Hi Wei,

 First, thanks for your reply. It is much clear now, and I still confuse that:

1) whether the process “The driver talks to the openwifi hardware”refers to the driver write registers?
2) Follow the previous question, the hostapd application provides a way for user to do the AP's operation, assuming that now a client want to connect with openwifi, it scan the beacon frame(ssid) from the openwifi and send the auth request, the driver report this request to upper layer, the auth response send operation is controled by mac80211(cfg or mlme?) or hostapd?
 
Best,
Shangjie

**Comment by weiliu1011** [comment]
Hi Shangjie,

1. Yes, talking to hardware means read/write registers.
2. I am no expert in this aspect, but likely authentication packets are generated by some program in user space, so not mac80211/cfg80211.

Best,
Wei

**Comment by Shangjie-Yang** [comment]
Hi Wei,
  Is that means when the system is running, some program run in the background(user space) help us to do the High mac operations? and these program need mac80211-module's help.

Best,
Shangjie
