### ISSUE TITLE
Recompiled sdr.ko won't load

### ISSUE THREAD

**Issue by frestuc** [open-sdr/openwifi#70]
I am using the default SD card image for openwifi 64 bit (board zcu102).
I have recompiled the driver sdr.ko and loaded it into the board, but when I execute wgd.sh I get the following:

```
[  342.566942] sdr: version magic '4.14.0-gb6e379910a11-dirty SMP mod_unload aarch64' should be '4.14.0-gb6e379910a11 SMP mod_unload aarch64'
```
Any hint?

**Comment by JiaoXianjun** [comment]
Like I said in previous issue, you need to follow: 

https://github.com/open-sdr/openwifi#build-openwifi-linux-img-from-scratch
