### ISSUE TITLE
802.11 packet injection

### ISSUE THREAD

**Issue by 18845725896peng** [open-sdr/openwifi#71]
hello,
    I ssh to the board and setup internet connection,when I input make,
   root@analog:~/openwifi/inject_80211# make
gcc  -Wall -Werror inject_80211.c -o inject_80211 -lpcap
In file included from inject_80211.c:22:0:
inject_80211.h:6:18: fatal error: pcap.h: No such file or directory
 #include <pcap.h>
                  ^
compilation terminated.
make: *** [inject_80211] Error 1

**Comment by JiaoXianjun** [comment]
What is your board type?
Are you using our image? Or you create your own image?

**Comment by 18845725896peng** [comment]
I use ZC706 and ad-fmcomms2-ebz and your image

**Comment by JiaoXianjun** [comment]
When do you download the image?

**Comment by 18845725896peng** [comment]
three months ago ,need I use the newest image?

**Comment by JiaoXianjun** [comment]
yes. please

**Comment by 18845725896peng** [comment]
thank you, I will try

**Comment by 18845725896peng** [comment]
it works , thank you
