### ISSUE TITLE
How can I  make modified sdr.c work?

### ISSUE THREAD

**Issue by 18845725896peng** [open-sdr/openwifi#72]
hello,
   when I modify the sdr.c ,how can I make it work?  Ssh to the board and compile it to generate sdr.ko, then insmod?

**Comment by JiaoXianjun** [comment]
You need to follow: https://github.com/open-sdr/openwifi#update-driver

**Comment by 18845725896peng** [comment]
thank you ,I get it

**Comment by BZZDKBRS** [comment]
> 你好， 当我修改 sdr.c 的时候，我能怎么板子工作？ssh到，编译生成 sdr.ko，然后insmod？
Hello, where did you modify the code?
What I know is to download the code in the virtual machine. But I just started to migrate openwifi. What configurations do I need for the virtual machine? May I see your orders?

**Comment by chenmo234** [comment]
I also need to modify sdr.c and perform the same operations as you. Can I discuss this with you? Here is my contact information: c2385405729.
