### ISSUE TITLE
QoS support

### ISSUE THREAD

**Issue by tommy782** [open-sdr/openwifi#73]
Hi,
Really thank you for this project, it is amazing!

I have a question please:
Are EDCA and HCCA supported?

Thanks,
Tommy

**Comment by weiliu1011** [comment]
Hi,
Thanks for appreciating the project. At the moment HCCA is not supported. EDCA is partially supported, we allow different contention window to be set for different queues in the transmitter, depending on the priority. But AIFS is not supported, all packets wait for at least DIFS. 
Best,
Wei

**Comment by tommy782** [comment]
Thank you for your help.

Best,
Tommy
