### ISSUE TITLE
Ping unsuccessful between two ad-hoc nodes

### ISSUE THREAD

**Issue by aaabbb414** [open-sdr/openwifi#77]
I am using Zedboard with FMCOMMS4 setup. I downloaded image in table with board_name: zed_fmcs2. 
I followed steps in https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/ad-hoc-two-sdr.md to configure two nodes. 
I could see both of them having same cell which I assume they are connected. However, "ping" keeps failing because "destination host unreachable". This happens for both nodes. 

I am wondering if there is any suggestion how to solve this? 

Thanks

**Comment by JiaoXianjun** [comment]
Hello,

Thanks for report. We just updated an issue template. Would you please answer:

0. Could you send email to xianjun.jiao@ugent.be to introduce your self?

1. Our image is used directly or you build your own image?

2. What is your own modification?

3. Versions: OS, Vivado, openwifi/openwifi-hw commit revision

4. Board/hardware type

5. WiFi channel number

6. Steps to reproduce the issue

7. Describe your debug efforts by Linux native tools, such as tcpdump and "cat /proc/interrupts"

8. Describe your debug efforts by: https://github.com/open-sdr/openwifi/blob/master/doc/README.md#Debug-methods

**Comment by JiaoXianjun** [comment]
Have you ping successfully?

**Comment by srushti1763** [comment]
Same issue

**Comment by amin57007** [comment]
i have the same issue too. please help me using ad-hoc in correct way and working persistant. i run this protocol to set ad-hoc and change frequency for using cleaner channel.

in one side :
cd openwifi
./wgd.sh 1
ifconfig sdr0 up
./sdr-ad-hoc-join.sh sdr0 8 192.168.13.1 96:44:8D:3A:21:20
iwconfig sdr0

./set_restrict_freq.sh 1500
./sdrctl dev sdr0 set reg rf 1 1500
./sdrctl dev sdr0 set reg rf 5 1500
./sdrctl dev sdr0 set reg rf 0 10000
./sdrctl dev sdr0 set reg drv_rx 7 7

in another side :
cd openwifi
./wgd.sh 1
ifconfig sdr0 up
./sdr-ad-hoc-join.sh sdr0 8 192.168.13.2 96:44:8D:3A:21:20
iwconfig sdr0

./set_restrict_freq.sh 1500
./sdrctl dev sdr0 set reg rf 1 1500
./sdrctl dev sdr0 set reg rf 5 1500
./sdrctl dev sdr0 set reg rf 0 10000
./sdrctl dev sdr0 set reg drv_rx 7 7
