### ISSUE TITLE
Ad9361  reg value, rx channel ,tx channel  freq config

### ISSUE THREAD

**Issue by L123ee** [open-sdr/openwifi#86]
According #24 ，I known the openwifi use FDD mode.  

But by directly reading the values of Ad9361 registers 0x271-0x275 and 0x231-0x235, it is found that AP's rx and STA's rx are the same configuration, and AP's tx and STA tx are the same configuration, as shown in the figure below。
![image](https://user-images.githubusercontent.com/32754932/125578496-324e7803-070c-4bc3-8303-14866cbb2a75.png)

Shouldn't the rx of AP be equal to tx of STA and the tx of AP equal to rx of STA?

Ｔｈａｎｋ　ｙｏｕ．

**Comment by JiaoXianjun** [comment]
If you read our project document carefully, you will find answer here:
https://github.com/open-sdr/openwifi/blob/master/doc/README.md#analog-and-digital-frequency-design
