### ISSUE TITLE
DSSS Support

### ISSUE THREAD

**Issue by jesusferrer** [open-sdr/openwifi#9]
Is there a plan to add DSSS / 802.11b support, and if so, what is the timeline?  How difficult would this be?

**Comment by JiaoXianjun** [comment]
We agree that 11.b would make the design more complete. But due to limited development resource, this feature has low priority.

**Comment by JiaoXianjun** [comment]
We have work around on 11b:

https://github.com/open-sdr/openwifi#special-note-for-11b

**Comment by JiaoXianjun** [comment]
Hello,

Thanks for reaching us.
Would you please introduce a bit yourself? Like company/university name, email, which country are your from, what is your role (student/employee) etc.?

In this way, we may help you further.
