### ISSUE TITLE
When can the WiFi6 avaliable?

### ISSUE THREAD

**Issue by sada45** [open-sdr/openwifi#97]
Hey guys:
The project is really intresting! 
May I ask when the WiFi6 feature can get online?
Thanks!

**Comment by JiaoXianjun** [comment]
We are developing. 
It is quite complicated. 
I hope early next year we could have some PHY functions ready.

Do you have fpga expertise and willing to contribute / work with us?

**Comment by dagelf** [comment]
Maybe you can share some good learning resources that you may have come across?

**Comment by JiaoXianjun** [comment]
Well.
Basically we read the standard, and then do implementation.
Of course during the procedure, necessary simulation and literature search help us understand the standard.
